"""Measure final GLBs and write ordinary project package-contract fields."""
import hashlib,importlib.util,json,math
from pathlib import Path
HERE=Path(__file__).resolve().parent
sp=importlib.util.spec_from_file_location('common',HERE.parent/'package-contract/validate.py');C=importlib.util.module_from_spec(sp);sp.loader.exec_module(C)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
def one(name,levels):
 ls=[]
 for level,stem in levels:
  glb=HERE/'exports'/(stem+'.glb');blend=HERE/'source'/(stem+'.blend');m=C.measure_glb(glb)
  ls.append({'level':level,'file':str(glb.relative_to(HERE)),'source':str(blend.relative_to(HERE)),'sha256':sha(glb),'sourceSha256':sha(blend),'componentsFile':str(glb.with_suffix('.components.json').relative_to(HERE)),'componentsSha256':sha(glb.with_suffix('.components.json')),**{k:v for k,v in m.items() if k not in ['nodeNames','materialNames']},'capabilities':{'passengerCapable':False,'doorsAnimated':False,'runtimeReady':False}})
 d,b=C.read_glb(HERE/ls[0]['file'])
 return {'id':name,'taskId':'B-CAB','variant':'Mark-V-A-car-representative-study' if 'study' in name else 'Mark-V-A-car-budget-candidate','kind':'transit-interior','source':ls[0]['source'],'sourceSha256':ls[0]['sourceSha256'],'lods':ls,'boundsM':ls[0]['boundsM'],'expectedDimensionsM':[2.558,2.4225,16.335],'dimensionToleranceM':.02,'dimensionBasis':'Authoring assumptions, not surveyed dimensions. Official model identity and A-car regional layout only.','pivot':{'frameId':'vehicle','positionM':[0,0,0],'meaning':'interior floor datum, longitudinal midpoint of body module'},'attachmentDatum':{'frameId':'vehicle','kind':'interior-floor','heightM':0},'frontAxis':'+Z','materialBindings':[{'material':m['name'],'semanticRole':m['name'],'sharedSurfaceId':'mark-v-'+m['name'],'primitiveSelection':{'materialName':m['name']},'maps':[]} for m in d['materials']],'textureMode':'embedded-original-PNG','textureCost':{'embeddedBytes':ls[0]['embeddedImageBytes'],'gpuRGBA8WithMipsEstimate':sum(i['texelBytesWithMips'] for i in ls[0]['images'])},'lodPolicy':{'switchDistances':'not assigned; requires actual runtime measurement','sourcePreservation':'high-detail master + separately editable reduced LOD sources','budgetScope':'study exempt as non-runtime visual reference; constrained pair checked against B-CAB caps'},'clearance':{'scope':'offline static conservative aisle samples only','standingHeightM':1.95,'capsuleRadiusM':.25,'referencePath':'qa/clearance-validation.json','doorState':'closed; no boardability claimed'},'collision':{'kind':'not runtime supplied','notes':'Component ranges support offline conservative envelopes; not a validated navigation/collision mesh.'},'anchors':{'frameId':'vehicle','seatCount':22,'layoutFile':'layout-assumptions.json','kind':'reference only; not bound to passenger adapter'},'placementCompatibility':{'status':'not_assumed','CanadaLine3m':False,'legacyExpoFourCar':False,'platforms':False,'kinematicGangway':False},'intendedConsumer':'future independent Mark V interior/profile integration after engineering review','offlineChecks':'qa/validation.json','runtimeChecks':{'status':'not_run','WebGL':'not_run','doorAnimation':'not_run','boarding':'not_run','movingCollision':'not_run','fullConsist':'not_run','lifecycle':'not_run','performance':'not_run'}}
def main():
 a=one('mark-v-a-car-interior',[(0,'mark-v-a-car-interior.lod0'),(1,'mark-v-a-car-interior.lod1')]);study=one('mark-v-a-car-study',[(0,'mark-v-a-car-study')])
 m={'schemaVersion':1,'packageId':'skytrain-mark-v-interior','version':'0.1.0','baseRevision':'a965982a58b5d15996af68899de021fa30f9267c','status':'offline_visual_candidate_runtime_not_run','units':'m','coordinateSystem':{'authoring':'Blender +Z up, -Y front','runtime':'glTF +Y up, +Z observation end','conversion':'(x,y,z) -> (x,z,-y) once'},'provenance':{'authoring':'Original photo-informed modeling, original texture generator, existing project primitive/batching utilities','model':'Alstom Mark V','line':'Expo','references':'REFERENCES.md','source':'https://github.com/YiTaChen/vancouver-living-atlas','project':'Vancouver Living Atlas by YiTaChen','license':'Vancouver Living Atlas Noncommercial Research and Attribution 1.0','referencePixelsDistributed':False,'textureGeneratorSha256':sha(HERE/'make_textures.py')},'reexportCommand':'blender -b -t 4 --python tools/assets/skytrain-mark-v-interior/export.py -- --output /tmp/mark-v-reexport','validationCommand':'python tools/assets/skytrain-mark-v-interior/validate.py','assets':[a,study],'textures':[{'file':str(p.relative_to(HERE)),'sha256':sha(p),'bytes':p.stat().st_size,'original':True,'generator':'make_textures.py'} for p in sorted((HERE/'textures').glob('*.png'))]}
 write(HERE/'manifest.json',m)
 write(HERE/'qa/measurements.json',{'scope':'actual final GLB transformed geometry and embedded images','runtimeMeasured':False,'assets':[{ 'id':a['id'],'lods':a['lods']} for a in m['assets']]})
 inv=[]
 for a in m['assets']:
  for l in a['lods']:
   d,b=C.read_glb(HERE/l['file']);inv.append({'file':l['file'],'sha256':l['sha256'],'materials':d['materials'],'textures':d.get('textures',[]),'images':l['images'],'lights':len(d.get('extensions',{}).get('KHR_lights_punctual',{}).get('lights',[])),'primitiveCount':l['primitives']})
 write(HERE/'qa/exported-material-inventory.json',{'scope':'actual exported PBR properties, not source shader assumptions','assets':inv})
if __name__=='__main__':main()
