const EN = {
  title: 'Light lab',
  place: 'Science World · Atlas activity',
  intro:
    'Walk through the annex into the dome, then use three beams to match a colour. Complete three experiments to earn your Light Lab stamp.',
  original:
    'An original Atlas activity inside our representative interior, not an official Science World exhibit.',
  open: 'Visit the light lab',
  start: 'Start at the entrance',
  resume: 'Return to the entrance',
  replay: 'Try the lab again',
  progress: 'experiments',
  stamped: 'Light Lab stamp earned',
  saved: 'Progress saved in this browser.',
  memory: 'Storage unavailable. Progress lasts for this visit.',
  close: 'Close light lab',
  pause: 'Pause activity',
  leave: 'Return to the city',
  approach: 'Walk through the annex and follow the gold markers into the dome.',
  return:
    'Your visit was interrupted. Return to the entrance to continue on foot.',
  nearby: 'Stand by the green demonstration island to use the light mixer.',
  ready: 'The mixer is ready. Step up and explore the beams.',
  interact: 'Use the light mixer',
  waypoint: 'Indoor waypoint',
  lab: 'Green demonstration island',
  join: 'Starting places you at the entrance. Reach each marker on foot; your experiment progress is kept.',
  failed:
    'The entrance route is not clear in this scene. Please try again after the city loads.',
  target: 'Target light',
  mixture: 'Your mixture',
  red: 'Red light',
  green: 'Green light',
  blue: 'Blue light',
  test: 'Test the mixture',
  retry: 'Keep experimenting. Match all three beam levels to the target light.',
  answer: 'Experiment recorded',
  complete: 'Three discoveries, one bright finish.',
  reset: 'Turn all beams off',
  practice: 'These are lights: adding more light makes the mixture brighter.',
  inaccessible:
    'Stay on foot at the demonstration island to adjust or test the mixer.',
  sources: 'How additive light works',
  titles: ['A yellow glow', 'A cyan glow', 'Bring back white light'],
  descriptions: [
    'Bright yellow light: combine two beams and leave the third off.',
    'Bright cyan light: change one beam from the previous mixture.',
    'White light: combine all three beams at equal full intensity.',
  ],
  hints: [
    'Red and green light together make yellow.',
    'Green and blue light together make cyan.',
    'Red, green and blue light together make white.',
  ],
  observations: [
    'Yellow can come from red and green light arriving together. Mixing light follows different rules from mixing paint.',
    'Green plus blue creates cyan. Turning a beam off removes its contribution; the remaining beams determine the colour.',
    'Equal full red, green and blue gives white. Reducing all three equally keeps a neutral colour while reducing brightness.',
  ],
  hint: 'Show a hint',
  collected: 'Your lab discoveries',
};
const HANT: typeof EN = {
  title: '光色實驗室',
  place: 'Science World · Atlas 活動',
  intro:
    '穿過入口大廳、走進圓頂，用三道色光調出指定顏色。完成三個實驗，收集光色實驗室印章。',
  original:
    '這是 Atlas 在示意室內空間設計的原創活動，並非 Science World 官方展覽。',
  open: '參觀光色實驗室',
  start: '從入口開始',
  resume: '回入口繼續',
  replay: '再次挑戰實驗室',
  progress: '個實驗',
  stamped: '獲得光色實驗室印章',
  saved: '進度已保存在這個瀏覽器。',
  memory: '瀏覽器無法儲存，進度僅保留於這次造訪。',
  close: '關閉光色實驗室',
  pause: '暫停活動',
  leave: '返回城市',
  approach: '穿過入口大廳，跟隨金色標記走進圓頂。',
  return: '參觀已中斷，請回到入口後步行前往實驗台。',
  nearby: '站到綠色展示台旁，就能操作混光器。',
  ready: '混光器準備好了，來試試三道色光。',
  interact: '操作混光器',
  waypoint: '室內導引點',
  lab: '綠色展示台',
  join: '開始時會移至入口。請步行經過各個標記；已完成的實驗會保留。',
  failed: '目前場景無法通過入口路線，請在城市載入後重試。',
  target: '目標色光',
  mixture: '你的混光',
  red: '紅光',
  green: '綠光',
  blue: '藍光',
  test: '測試混光',
  retry: '繼續試試看，調整三道色光的強度，讓混光接近目標。',
  answer: '實驗已記錄',
  complete: '三次發現，點亮一枚印章。',
  reset: '關閉所有色光',
  practice: '這裡混合的是光：加入更多色光，混光會變亮。',
  inaccessible: '請保持步行模式，站在展示台旁調整或測試混光器。',
  sources: '了解光的加色混合',
  titles: ['調出明亮的黃光', '調出明亮的青光', '找回白光'],
  descriptions: [
    '明亮的黃色：混合兩道色光，關閉第三道。',
    '明亮的青色：從剛才的配方換掉一道色光。',
    '白色：將三道色光調成相同的最大強度。',
  ],
  hints: [
    '紅光與綠光混合，可以得到黃光。',
    '綠光與藍光混合，可以得到青光。',
    '紅、綠、藍三道色光一起照射，可以得到白光。',
  ],
  observations: [
    '紅光與綠光同時進入眼睛，可以呈現黃色。混合色光與混合顏料，遵循不同的規則。',
    '綠光加上藍光形成青色。關掉一道色光，就移除了它的貢獻，剩下的光決定混合後的顏色。',
    '等量、全強度的紅綠藍色光混合成白光。一起降低三者的強度，顏色保持中性，亮度則會下降。',
  ],
  hint: '顯示提示',
  collected: '你的實驗發現',
};
const HANS: typeof EN = {
  title: '光色实验室',
  place: 'Science World · Atlas 活动',
  intro:
    '穿过入口大厅、走进圆顶，用三道色光调出指定颜色。完成三个实验，收集光色实验室印章。',
  original:
    '这是 Atlas 在示意室内空间设计的原创活动，并非 Science World 官方展览。',
  open: '参观光色实验室',
  start: '从入口开始',
  resume: '回入口继续',
  replay: '再次挑战实验室',
  progress: '个实验',
  stamped: '获得光色实验室印章',
  saved: '进度已保存在这个浏览器。',
  memory: '浏览器无法储存，进度仅保留于这次访问。',
  close: '关闭光色实验室',
  pause: '暂停活动',
  leave: '返回城市',
  approach: '穿过入口大厅，跟随金色标记走进圆顶。',
  return: '参观已中断，请回到入口后步行前往实验台。',
  nearby: '站到绿色展示台旁，就能操作混光器。',
  ready: '混光器准备好了，来试试三道色光。',
  interact: '操作混光器',
  waypoint: '室内引导点',
  lab: '绿色展示台',
  join: '开始时会移至入口。请步行经过各个标记；已完成的实验会保留。',
  failed: '目前场景无法通过入口路线，请在城市加载后重试。',
  target: '目标色光',
  mixture: '你的混光',
  red: '红光',
  green: '绿光',
  blue: '蓝光',
  test: '测试混光',
  retry: '继续试试看，调整三道色光的强度，让混光接近目标。',
  answer: '实验已记录',
  complete: '三次发现，点亮一枚印章。',
  reset: '关闭所有色光',
  practice: '这里混合的是光：加入更多色光，混光会变亮。',
  inaccessible: '请保持步行模式，站在展示台旁调整或测试混光器。',
  sources: '了解光的加色混合',
  titles: ['调出明亮的黄光', '调出明亮的青光', '找回白光'],
  descriptions: [
    '明亮的黄色：混合两道色光，关闭第三道。',
    '明亮的青色：从刚才的配方换掉一道色光。',
    '白色：将三道色光调成相同的最大强度。',
  ],
  hints: [
    '红光与绿光混合，可以得到黄光。',
    '绿光与蓝光混合，可以得到青光。',
    '红、绿、蓝三道色光一起照射，可以得到白光。',
  ],
  observations: [
    '红光与绿光同时进入眼睛，可以呈现黄色。混合色光与混合颜料，遵循不同的规则。',
    '绿光加上蓝光形成青色。关掉一道色光，就移除了它的贡献，剩下的光決定混合后的颜色。',
    '等量、全强度的红绿蓝色光混合成白光。一起降低三者的强度，颜色保持中性，亮度则会下降。',
  ],
  hint: '显示提示',
  collected: '你的实验发现',
};
export function lightLabCopy(locale: string) {
  return locale === 'zh-Hant' ? HANT : locale === 'zh-Hans' ? HANS : EN;
}
