"""Single numerical contract, explicit representative dimensions, glTF Y-up metre frames."""
import json,math,sys,importlib.util,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parent
spec=importlib.util.spec_from_file_location('common',ROOT.parent/'package-contract/validate.py');common=importlib.util.module_from_spec(spec);spec.loader.exec_module(common)
PROFILE='expo-metro-17m'
BASE='8b95f013297597845d542463d6ce635105a95c4f'
IDENT=[0,0,0,1]
def transform(p,parent='vehicle'):return {'parentFrameId':parent,'translationM':p,'rotationQuaternionXYZW':IDENT,'scale':[1,1,1]}
def rect(x0,x1,y,z0,z1):return [[x0,y,z0],[x1,y,z0],[x1,y,z1],[x0,y,z1]]
def bounds(a,b):return {'min':a,'max':b,'size':[b[i]-a[i] for i in range(3)]}
def vehicle(variant):
 vid=f'expo-metro-{variant}';v={'vehicleId':vid,'profileId':PROFILE,'variant':variant,'frameId':'vehicle','units':'m','assetRefs':{'exterior':vid+'-exterior','interior':'expo-metro-shared-interior','collision':None},'bodyBoundsM':bounds([-1.325,.93,-8.5],[1.325,3.12,8.5]),'nominalLengthM':17,'nominalBodyWidthM':2.65,'railContactDatum':{'frameId':'vehicle','planeY':0,'nodeIds':[]},'floorHeightM':.95,'doorSillHeightM':.95,'ceilingUndersideM':3.11,'headroomM':2.11,'clearAisleWidthM':1.25,'legacyToVehicleRoot':{'status':'not_a_direct_replacement','translationM':[0,-.02,0],'rotationQuaternionXYZW':IDENT,'scale':[1,1,1],'note':'Historical wheel contact Y≈0.02 to new datum only; no legacy body center is reused for floor/door metadata.'},'frames':[{'frameId':'vehicle','parentFrameId':None,'units':'m','upAxis':'+Y','frontAxis':'+Z','translationM':[0,0,0],'rotationQuaternionXYZW':IDENT,'scale':[1,1,1]}],'floorSurfaces':[{'surfaceId':'continuous-cabin-floor','nodeId':'floor','frameId':'vehicle','verticesM':rect(-1.225,1.225,.95,-8.5,8.5),'indices':[0,2,1,0,3,2],'walkableSubset':'standingRegions exclude seat and wall obstacles'}],'doors':[],'bogies':[],'wheels':[],'seats':[],'standingRegions':[],'cameraAnchors':[],'gangways':[],'couplers':[],'anchors':[],'collision':{'frameId':'vehicle','type':'primitives','primitives':[],'precision':'Representative gameplay proxies; CPU sampled against delivered mesh. Dynamic leaf proxies follow door node.'},'freeZones':[]}
 def anchor(name,p,resource='exterior'):
  v['anchors'].append({'nodeId':name,'frameId':'vehicle','positionM':p,'resource':resource});return name
 for side,x in [('right',-1.321),('left',1.321)]:
  sign=-1 if side=='right' else 1
  for pos,z in [('rear',-5.5),('center',0),('front',5.5)]:
   for leaf,delta in [('a',-.35),('b',.35)]:
    name=f'door-{side}-{pos}-{leaf}';p=[x,.95,z+delta];q=[x+sign*.11,.95,z+delta+(-.73 if leaf=='a' else .73)]
    fr={'frameId':name,**transform(p)};v['frames'].append(fr)
    v['doors'].append({'doorId':name,'nodeId':name,'frameId':'vehicle','doorFrameId':name,'parentFrameId':'vehicle','carId':vid,'side':side,'openingId':f'{side}-{pos}','openingPolygonM':[[sign*1.28,.95,z-.7],[sign*1.28,.95,z+.7],[sign*1.28,3.0,z+.7],[sign*1.28,3.0,z-.7]],'openingWidthM':1.4,'openingHeightM':2.05,'outwardNormal':[sign,0,0],'closedTransform':transform(p),'openTransform':transform(q),'animation':{'type':'transform-endpoints','nodeId':name,'durationS':1.2,'interpolation':'two-stage-plug-then-slide','plugTravelM':.11,'slideTravelM':.73},'sweptBoundsM':{'frameId':'vehicle',**bounds([min(p[0],q[0])-.0275,.95,min(p[2],q[2])-.345],[max(p[0],q[0])+.0275,3,max(p[2],q[2])+.345])},'boardingPointM':[sign*1.65,.95,z],'boardingAnchorNodeId':anchor(f'boarding-{side}-{pos}',[sign*1.65,.95,z]) if leaf=='a' else f'boarding-{side}-{pos}','doorLocalToVehicle':transform(p),'leafBoundsLocalM':bounds([-.0275,0,-.345],[.0275,2.05,.345])})
 for b,z in [('rear',-5.65),('front',5.65)]:
  v['bogies'].append({'bogieId':'bogie-'+b,'nodeId':'bogie-'+b,'frameId':'vehicle','centerM':[0,.36,z],'axleWheelbaseM':1.36,'semanticRole':'steel-bogie-frame','material':'metro-steel-metal'});v['frames'].append({'frameId':'bogie-'+b,**transform([0,.36,z])})
  for axle,dz in [('rear',-.68),('front',.68)]:
   for side,x in [('right',-1.12),('left',1.12)]:
    name=f'wheel-{b}-{axle}-{side}';p=[x,.36,z+dz];v['wheels'].append({'nodeId':name,'frameId':'vehicle','bogieId':'bogie-'+b,'axleId':f'{b}-{axle}','centerM':p,'radiusM':.36,'widthM':.16,'spinAxis':[1,0,0],'semanticRole':'steel-rail-wheel','material':'metro-steel-metal'});v['railContactDatum']['nodeIds'].append(name)
 for side,e in [('right',-1),('left',1)]:
  for pos,z in [('rear',-5.5),('center',0),('front',5.5)]:
   v['floorSurfaces'].append({'surfaceId':f'threshold-{side}-{pos}','nodeId':'body-shell','frameId':'vehicle','resource':'exterior','verticesM':rect(min(e*1.225,e*1.325),max(e*1.225,e*1.325),.95,z-.7,z+.7),'indices':[0,2,1,0,3,2]})
  for j,(a,b) in enumerate([(-8.5,-6.2),(-4.8,-.7),(.7,4.8),(6.2,8.5)]):
   v['collision']['primitives'].append({'id':f'wall-{side}-{j}','frameId':'vehicle','nodeId':'body-shell','type':'box','boundsM':bounds([min(e*1.213,e*1.335),.95,a],[max(e*1.213,e*1.335),3.12,b]),'reason':'Conservative solid wall+window proxy, excludes actual door openings'})
 v['guidanceWheelbaseM']=11.3
 for side,x in [('right',-.96),('left',.96)]:
  for i,z in enumerate([-7.1,-3,-2.3,2.3,3,7.1]):
   name=f'seat-{side}-{i+1:02d}';p=[x,1.40,z];eye=[x,2.05,z];facing=[0,math.sin((math.pi/2 if x<0 else -math.pi/2)/2),0,math.cos(math.pi/4)]
   v['seats'].append({'seatId':name,'nodeId':name,'frameId':'vehicle','pelvisPointM':p,'pelvisAnchorNodeId':anchor(name+'-pelvis',p,'interior'),'facingQuaternionXYZW':facing,'cameraEyePointM':eye,'cameraAnchorNodeId':anchor(name+'-camera',eye,'interior'),'seatWidthM':.46,'seatDepthM':.46,'seatHeightAboveFloorM':.45,'priority':side=='left' and i in (0,5),'entryFeetPointM':[math.copysign(.56,x),.95,z],'referenceBody':'pelvis datum; consumer must solve rig root offset'})
   v['collision']['primitives'].append({'id':name+'-obstacle','frameId':'vehicle','nodeId':name,'type':'box','boundsM':bounds([min(x-.23,math.copysign(1.2075,x)),.95,z-.23],[max(x+.23,math.copysign(1.2075,x)),1.92,z+.23]),'reason':'Seat cushion/back/support conservative union'})
  for z in [-4.15,-1.2,1.2,4.15]:
   if (x>0 and z==-4.15) or (x<0 and z==4.15):continue
   v['collision']['primitives'].append({'id':f'rail-{side}-{z}','frameId':'vehicle','nodeId':'handrails','type':'cylinder','centerM':[math.copysign(.67,x),2.01,z],'radiusM':.018,'heightM':2.12,'axis':[0,1,0]})
 for name,z in [('rear-vestibule',-5.5),('central-vestibule',0),('front-vestibule',5.5)]:
  p=[0,.95,z];v['standingRegions'].append({'regionId':name,'frameId':'vehicle','polygonM':rect(-1.19,1.19,.95,z-.62,z+.62),'feetPointM':p,'headClearanceM':2.11,'anchorNodeId':anchor(name,p,'interior')})
 v['standingRegions'].append({'regionId':'aisle','frameId':'vehicle','polygonM':rect(-.62,.62,.95,-8.25,8.25),'feetPointM':[0,.95,0],'headClearanceM':2.11,'anchorNodeId':anchor('aisle-stand',[0,.95,0],'interior')})
 for name,x0,x1,z0,z1 in [('wheelchair',.25,1.17,-4.70,-3.55),('bicycle',-1.17,-.25,3.55,4.70)]:
  v['freeZones'].append({'zoneId':name,'frameId':'vehicle','polygonM':rect(x0,x1,.95,z0,z1),'emptyRequired':True,'note':'Representative gameplay free-space target, no accessibility certification.'})
 for name,p in [('aisle-eye',[0,2.55,-7.8]),('observation-front',[0,2.55,8.0]),('observation-rear',[0,2.55,-8.0])]:v['cameraAnchors'].append({'cameraId':name,'frameId':'vehicle','positionM':p,'nodeId':anchor(name,p,'interior')})
 for end,z in [('front',8.9),('rear',-8.9)]:
  e=1 if z>0 else -1;v['couplers'].append({'couplerId':end,'semanticRole':'steel-coupler','material':'metro-steel-metal','frameId':'vehicle','positionM':[0,.64,z],'outwardNormal':[0,0,e],'anchorNodeId':anchor('coupler-'+end,[0,.64,z])})
  observation=(variant=='lead' and e==1) or (variant=='tail' and e==-1)
  if observation:
   v['collision']['primitives'].append({'id':'observation-end-'+end,'frameId':'vehicle','nodeId':'body-shell','type':'box','boundsM':bounds([-1.325,.95,min(e*8.41,e*8.5)],[1.325,3.12,max(e*8.41,e*8.5)]),'reason':'End body/window solid collision, observation window is not a boarding opening'})
  if not observation:
   for side,x in [('right',-.9525),('left',.9525)]:v['collision']['primitives'].append({'id':f'gangway-jamb-{end}-{side}','frameId':'vehicle','nodeId':'body-shell','type':'box','boundsM':bounds([x-.3725,.94,min(e*8.41,e*8.5)],[x+.3725,3.05,max(e*8.41,e*8.5)])})
   v['collision']['primitives'].append({'id':'gangway-header-'+end,'frameId':'vehicle','nodeId':'body-shell','type':'box','boundsM':bounds([-.70,3.0,min(e*8.41,e*8.8)],[.70,3.12,max(e*8.41,e*8.8)]),'reason':'Conservative union of end header and bellows header'})
   v['floorSurfaces'].append({'surfaceId':'gangway-bridge-'+end,'nodeId':'body-shell','frameId':'vehicle','resource':'exterior','verticesM':rect(-.58,.58,.95,min(e*8.5,e*8.8),max(e*8.5,e*8.8)),'indices':[0,2,1,0,3,2]})
   v['collision']['primitives'].append({'id':'gangway-bridge-'+end,'frameId':'vehicle','nodeId':'body-shell','type':'box','boundsM':bounds([-.58,.88,min(e*8.5,e*8.8)],[.58,.95,max(e*8.5,e*8.8)])})
   name='gangway-'+end;p=[0,.95,e*8.5];v['frames'].append({'frameId':name,**transform(p)})
   v['gangways'].append({'gangwayId':name,'frameId':'vehicle','gangwayFrameId':name,'parentFrameId':'vehicle','positionM':p,'anchorNodeId':anchor(name,p),'outwardNormal':[0,0,e],'walkablePolygonM':rect(-.58,.58,.95,min(e*8.4,e*8.8),max(e*8.4,e*8.8)),'clearWidthM':1.16,'clearHeightM':2.05,'telescopingRangeM':[.20,.45],'curveSweep':{'frameId':'vehicle','yawRangeRadians':[-.12,.12],'sweptBoundsM':bounds([-.82,.88,min(e*8.35,e*9.15)],[.82,3.15,max(e*8.35,e*9.15)]),'status':'conservative offline envelope; moving inter-car collision not accepted'},'intercarTraversalEnabled':False})
 v['observationEnds']=[end for end,e in [('front',1),('rear',-1)] if (variant=='lead' and e==1) or (variant=='tail' and e==-1)]
 v['lodCapabilities']=[{'level':i,'doorsAnimated':i<2,'passengerCapable':i<2,'openingsPreserved':i<2,'interiorLevel':min(i,1) if i<2 else None,'stateRestriction':'closed, empty, nonboardable display only' if i==2 else 'interior must be loaded before passengers/boarding'} for i in range(3)]
 v['collision']['primitives'].append({'id':'continuous-floor','frameId':'vehicle','nodeId':'floor','type':'box','boundsM':bounds([-1.225,.88,-8.5],[1.225,.95,8.5])})
 v['collision']['primitives'].append({'id':'ceiling','frameId':'vehicle','nodeId':'ceiling','type':'box','boundsM':bounds([-1.225,3.11,-8.5],[1.225,3.17,8.5])})
 v['collision']['dynamicDoorPolicy']='Use each leafBoundsLocalM transformed by its current door node; opening metadata is full paired doorway.'
 return v

def write_manifest():
 assets=[];measurements=[]
 for name,kind,n in [('lead','exterior',3),('middle','exterior',3),('tail','exterior',3),('shared','interior',2)]:
  aid=f'expo-metro-{name}-{kind}';lods=[];names=set()
  for i in range(n):
   stem=f'{aid}.lod{i}';f='exports/'+stem+'.glb';s='source/'+stem+'.blend';r=common.measure_glb(ROOT/f);names.update(r['materialNames']);batch_info=common.read_glb(ROOT/f)[0].get('extras',{}).get('staticBatching');l={'level':i,'file':f,'sha256':common.digest(ROOT/f),'source':s,'sourceSha256':common.digest(ROOT/s),**{k:r[k] for k in ['triangles','vertices','primitives','bytes','boundsM','geometryBytes','embeddedImageBytes']},'doorsAnimated':kind=='exterior' and i<2,'passengerCapable':i<2,'openingsPreserved':i<2};
   if batch_info:l['staticBatching']={**batch_info,'geometryProvenance':'GLB nodes[].extras.componentRanges; exact vertex/index ranges with original source node and source primitive'}
   lods.append(l);measurements.append({'assetId':aid,'level':i,**r})
  assets.append({'id':aid,'taskId':'D04' if kind=='exterior' else 'D05','variant':name,'kind':kind,'source':lods[0]['source'],'sourceSha256':lods[0]['sourceSha256'],'lods':lods,'boundsM':lods[0]['boundsM'],'expectedDimensionsM':{'bodyLength':17,'bodyWidth':2.65,'roofWidth':2.8,'floorY':.95,'ceilingUndersideY':3.11} if kind=='exterior' else {'floorWidth':2.45,'floorLength':17,'floorY':.95},'dimensionToleranceM':.02,'dimensionBasis':'Representative project target from AI_AGENT_DEVELOPMENT_BACKLOG.md §6.2; no exact MKII/III/V reproduction','pivot':{'frameId':'vehicle','positionM':[0,0,0],'meaning':'midpoint between bogies; rail contact datum'},'attachmentDatum':{'frameId':'vehicle','type':'rail-contact','planeY':0},'frontAxis':'+Z','materialBindings':[{'material':mat,'semanticRole':mat.removeprefix('metro-'),'surfaceId':'shared-'+mat,'maps':[],'vertexColor':'Tint' if mat=='metro-paint' else None} for mat in sorted(names)],'materialBudgetNote':'Four primary exterior roles paint/steel-metal/glass/lights plus secondary gangway-bellows rubber. This is one secondary role above the proposed four-role total; exact primitive costs are reported. Interior has dedicated semantic roles.','textureMode':'shared-role-no-images','textureCost':{'geometryBytes':sum(l['geometryBytes'] for l in lods),'embeddedImageBytes':0,'glbTotalBytes':sum(l['bytes'] for l in lods),'uniqueTexelBytesWithMips':0},'lodPolicy':{'suggestedDistancesM':[40,120] if kind=='exterior' else [20],'hysteresisM':8,'lazyLoad':kind=='interior','passengerLock':'LOD0/1 plus interior loaded; LOD2 closed empty display only'},'clearance':{'floorY':.95,'ceilingUndersideY':3.11,'headroomM':2.11,'aisleWidthM':1.25,'doorWidthM':1.4,'doorHeightM':2.05},'collision':{'type':'JSON-primitives','source':'vehicles[].collision','dynamicDoors':'vehicles[].doors[].leafBoundsLocalM'},'anchors':{'source':'vehicles[].anchors','frameId':'vehicle'},'placementCompatibility':{'profiles':[PROFILE],'scale':[1,1,1],'requires':'new car-local datum and station alignment; preserve existing route source'},'intendedConsumer':'lib/city/railway.ts (future explicit asset adapter; not enabled)','offlineChecks':{'status':'pending','evidence':'qa/validation.json'},'runtimeChecks':{'status':'not_run','reason':'D06 and WebGL integration outside offline asset scope'}})
 vehicles=[vehicle(x) for x in ['lead','middle','tail']]
 for v in vehicles:v['completeBoundsM']=next(a['boundsM'] for a in assets if a['id']==v['assetRefs']['exterior'])
 m={'schemaVersion':1,'packageId':'boardable-metro','version':'1.0.0','baseRevision':BASE,'status':'partial','units':'m','coordinateSystem':{'runtime':'glTF Y-up, +Z forward, -X right','authoring':'Blender Z-up, -Y forward','conversion':'(x,y,z) Blender -> (x,z,-y) glTF exactly once'},'provenance':{'author':'Original representative procedural mesh for Vancouver Living Atlas by YiTaChen','source':'https://github.com/YiTaChen/vancouver-living-atlas','license':'Vancouver Living Atlas Noncommercial Research and Attribution 1.0; repository LICENSE applies','references':['docs/AI_AGENT_DEVELOPMENT_BACKLOG.md §6.2–6.6','lib/city/railway.ts (legacy dimensions and incompatibility only)'],'copiedImagesOrMeshes':False,'modelIdentity':'expo-metro-17m four-car representative; not Mark V or exact Mark II/III'},'reexportCommand':'blender -b -t 2 --python tools/assets/boardable-metro/export.py -- --output /tmp/metro-reexport','validationCommand':'python tools/assets/boardable-metro/validate.py','assets':assets,'textures':[],'vehicles':vehicles,'composition':{'profileId':PROFILE,'frameId':'consist','cars':[{'carId':'car-01','vehicleId':'expo-metro-lead','translationM':[0,0,26.85],'rotationQuaternionXYZW':IDENT},{'carId':'car-02','vehicleId':'expo-metro-middle','translationM':[0,0,8.95],'rotationQuaternionXYZW':IDENT},{'carId':'car-03','vehicleId':'expo-metro-middle','translationM':[0,0,-8.95],'rotationQuaternionXYZW':IDENT},{'carId':'car-04','vehicleId':'expo-metro-tail','translationM':[0,0,-26.85],'rotationQuaternionXYZW':IDENT}],'nominalBodyLengthM':68,'carPitchM':17.9,'actualBoundsM':bounds([-1.4,0,-35.75],[1.4,3.48,35.75]),'actualLengthM':71.5,'betweenCarBodyGapM':.9,'couplerTipGapM':.1,'gangwayBridgeGapM':.3,'requiredPlatformLengthM':73.5,'stoppingToleranceEachEndM':1,'movingIntercarTraversal':'not_supported_pending_seam_and_moving_collision_validation'},'runtimeChecks':{'status':'not_run','integrationStatus':'runtime_pending_webgl','D06':'not_implemented'}}
 (ROOT/'manifest.json').write_text(json.dumps(m,indent=2)+'\n');(ROOT/'qa/measurements.json').write_text(json.dumps({'status':'measured','method':'actual GLB transformed scene-node accessors','results':measurements,'uniqueTexelBytesWithMips':0,'runtimeGpuMeasured':False},indent=2)+'\n')
if __name__=='__main__':write_manifest()
