'use client';
import { useEffect,useRef,useState } from 'react';
import { ArrowUpRight,Compass,Plus,Minus,RotateCcw,MapPin,Mountain,MoveUpRight } from 'lucide-react';
import { DEFAULT_SETTINGS,VIEWS,type SceneStats } from '@/lib/city/types';
import type { CityEngine } from '@/lib/city/engine';
export default function Home(){
 const host=useRef<HTMLDivElement>(null),engine=useRef<CityEngine|null>(null);const[ready,setReady]=useState(false),[error,setError]=useState(''),[view,setView]=useState('overview'),[stats,setStats]=useState<SceneStats>({buildings:0,roads:0,trees:0,fps:0,distance:0,elevation:0});
 useEffect(()=>{let stop=false;import('@/lib/city/engine').then(({CityEngine})=>{if(stop||!host.current)return;try{engine.current=new CityEngine(host.current,setStats,()=>setReady(true),setError);}catch(e){setError(String(e));}});return()=>{stop=true;engine.current?.destroy();};},[]);
 return <main className="atlas"><div className="scene" ref={host}/><header className="masthead"><a className="brand" href="/" aria-label="Vancouver Living Atlas"><span className="brand-mark"><Mountain size={22}/></span><span>VANCOUVER<span className="brand-sub">LIVING ATLAS / 溫哥華立體地圖</span></span></a><div className="header-meta"><span className="status-dot"/>BRITISH COLUMBIA, CANADA<span className="coord">49°17′ N · 123°08′ W</span></div><a className="github-link" href="https://github.com/YiTaChen/vancouver-living-atlas" target="_blank" rel="noreferrer">Open source <ArrowUpRight size={15}/></a></header>
 <section className="explore-panel glass"><div className="eyebrow">EXPLORE THE COAST</div><h1>一座山海之間的城市</h1><p className="panel-intro">沿著街道、森林與海岸，<br/>重新認識溫哥華。</p><div className="view-list">{VIEWS.slice(0,6).map((v,i)=><button key={v.id} className={`view-button ${view===v.id?'selected':''}`} onClick={()=>{setView(v.id);engine.current?.flyTo(v.id);}}><span className="view-number">0{i+1}</span><span><b>{v.name}</b><small>{v.zh}</small></span><MoveUpRight size={15}/></button>)}</div><div className="panel-foot"><span className="status-dot"/> REAL GEOGRAPHY · ORIGINAL 3D</div></section>
 <div className="nav-tools glass"><button title="放大" aria-label="放大" onClick={()=>engine.current?.zoom(.75)}><Plus size={20}/></button><button title="縮小" aria-label="縮小" onClick={()=>engine.current?.zoom(1.33)}><Minus size={20}/></button><span/><button title="回到全景" aria-label="回到全景" onClick={()=>{setView('overview');engine.current?.flyTo('overview');}}><RotateCcw size={18}/></button><button title="朝向北方" aria-label="朝向北方" onClick={()=>engine.current?.fly({...VIEWS[0],azimuth:0})}><Compass size={20}/></button></div>
 <footer className="bottom-bar glass"><div><MapPin size={15}/><b>{VIEWS.find(v=>v.id===view)?.name}</b><span className="muted">{stats.distance.toLocaleString()} m 視距</span></div><div className="scene-count"><span>{stats.buildings.toLocaleString()} 建築輪廓</span><span>地面 {stats.elevation} m</span><span>{stats.fps} FPS</span></div><p>拖曳旋轉 · 滾輪縮放 · 右鍵平移</p></footer>
 {!ready&&<div className="loading-overlay"><div className="loading-brand"><Mountain size={40}/><h2>VANCOUVER</h2><p>{error?'地圖載入未完成':'正在鋪展城市與海岸…'}</p>{error?<><p>{error}</p><button onClick={()=>location.reload()}>重新載入</button></>:<div className="loading-line"/>}</div></div>}
 </main>;
}
