"""Independent Canada Line representative profile; D04/D05-compatible, metre glTF frames."""
import importlib.util,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parent
sp=importlib.util.spec_from_file_location('atlas_common_contract',ROOT.parent/'package-contract/validate.py');common=importlib.util.module_from_spec(sp);sp.loader.exec_module(common)
PROFILE='canada-line-2car-representative-v1'
BASE='9efce79601deac6a0648cf8e158f3935cbb46f51'
IDENT=[0,0,0,1]
FLOOR=1.10
DOOR_Z=[-6.4,0,6.4]
def transform(p,parent='vehicle'):return {'parentFrameId':parent,'translationM':p,'rotationQuaternionXYZW':IDENT,'scale':[1,1,1]}
def rect(x0,x1,y,z0,z1):return [[x0,y,z0],[x1,y,z0],[x1,y,z1],[x0,y,z1]]
def bounds(a,b):return {'min':a,'max':b,'size':[b[i]-a[i] for i in range(3)]}
def vehicle():
 v={'vehicleId':'canada-line-endcar','profileId':PROFILE,'variant':'reversible-endcar','frameId':'vehicle','units':'m','assetRefs':{'exterior':'canada-line-endcar-exterior','interior':'canada-line-shared-interior','collision':None},'bodyBoundsM':bounds([-1.5,1,-10.25],[1.5,3.65,10.25]),'nominalLengthM':20.5,'nominalBodyWidthM':3,'railContactDatum':{'frameId':'vehicle','planeY':0,'nodeIds':[]},'floorHeightM':FLOOR,'doorSillHeightM':FLOOR,'ceilingUndersideM':3.45,'headroomM':2.35,'clearAisleWidthM':1.35,'guidanceWheelbaseM':13.5,'frames':[{'frameId':'vehicle','parentFrameId':None,'units':'m','upAxis':'+Y','frontAxis':'+Z','translationM':[0,0,0],'rotationQuaternionXYZW':IDENT,'scale':[1,1,1]}],'floorSurfaces':[{'surfaceId':'cabin-floor','nodeId':'floor','frameId':'vehicle','resource':'interior','verticesM':rect(-1.4,1.4,FLOOR,-10.25,10.16),'indices':[0,2,1,0,3,2]}],'doors':[],'bogies':[],'wheels':[],'seats':[],'standingRegions':[],'cameraAnchors':[],'gangways':[],'couplers':[],'anchors':[],'freeZones':[],'collision':{'frameId':'vehicle','type':'primitives','precision':'Representative gameplay proxies, sampled against actual GLB; not certification.','primitives':[],'dynamicDoorPolicy':'leafBoundsLocalM transformed by current door node pose; never retain closed collision when opening'}}
 def anchor(n,p,res='exterior'):
  v['anchors'].append({'nodeId':n,'frameId':'vehicle','positionM':p,'resource':res});return n
 for side,sign in [('left',1),('right',-1)]:
  for ordinal,z in enumerate(DOOR_Z):
   opening=f'{side}-{ordinal+1}';boarding=anchor('boarding-'+opening,[sign*1.7,FLOOR,z])
   v['floorSurfaces'].append({'surfaceId':'threshold-'+opening,'nodeId':'body-shell','frameId':'vehicle','resource':'exterior','verticesM':rect(min(sign*1.4,sign*1.5),max(sign*1.4,sign*1.5),FLOOR,z-.75,z+.75),'indices':[0,2,1,0,3,2]})
   for leaf,dz in [('a',-.375),('b',.375)]:
    name='door-'+opening+'-'+leaf;p=[sign*1.495,FLOOR,z+dz];q=[sign*1.625,FLOOR,z+dz+(-.79 if leaf=='a' else .79)]
    v['frames'].append({'frameId':name,**transform(p)})
    v['doors'].append({'doorId':name,'nodeId':name,'frameId':'vehicle','doorFrameId':name,'parentFrameId':'vehicle','carId':v['vehicleId'],'side':side,'openingId':opening,'openingPolygonM':[[sign*1.46,FLOOR,z-.75],[sign*1.46,FLOOR,z+.75],[sign*1.46,3.23,z+.75],[sign*1.46,3.23,z-.75]],'openingWidthM':1.5,'openingHeightM':2.13,'outwardNormal':[sign,0,0],'closedTransform':transform(p),'openTransform':transform(q),'animation':{'type':'transform-endpoints','nodeId':name,'durationS':1.4,'interpolation':'two-stage-plug-then-slide','plugTravelM':.13,'slideTravelM':.79},'sweptBoundsM':{'frameId':'vehicle',**bounds([min(p[0],q[0])-.03,FLOOR,min(p[2],q[2])-.369],[max(p[0],q[0])+.03,3.23,max(p[2],q[2])+.369])},'boardingPointM':[sign*1.7,FLOOR,z],'boardingAnchorNodeId':boarding,'doorLocalToVehicle':transform(p),'leafBoundsLocalM':bounds([-.03,0,-.369],[.03,2.13,.369])})
  for i,(a,b) in enumerate([(-10.25,-7.15),(-5.65,-.75),(.75,5.65),(7.15,10.25)]):
   v['collision']['primitives'].append({'id':f'wall-{side}-{i}','nodeId':'body-shell','frameId':'vehicle','type':'box','boundsM':bounds([min(sign*1.4,sign*1.53),FLOOR,a],[max(sign*1.4,sign*1.53),3.45,b])})
 for name,z in [('rear',-6.75),('front',6.75)]:
  p=[0,.39,z];v['frames'].append({'frameId':'bogie-'+name,**transform(p)});v['bogies'].append({'bogieId':'bogie-'+name,'nodeId':'bogie-'+name,'frameId':'vehicle','centerM':p,'axleWheelbaseM':2.15,'semanticRole':'steel-bogie-frame','material':'canada-steel'})
  for axle,dz in [('rear',-1.075),('front',1.075)]:
   for side,x in [('right',-.775),('left',.775)]:
    n=f'wheel-{name}-{axle}-{side}';v['wheels'].append({'nodeId':n,'frameId':'vehicle','bogieId':'bogie-'+name,'axleId':name+'-'+axle,'centerM':[x,.39,z+dz],'radiusM':.39,'widthM':.14,'spinAxis':[1,0,0],'semanticRole':'steel-rail-wheel','material':'canada-steel'});v['railContactDatum']['nodeIds'].append(n)
 for side,sign in [('left',1),('right',-1)]:
  for i,z in enumerate([-8.7,-7.95,-4.6,-3.85,-3.1,2.65,3.4,4.15,8.05,8.8]):
   # Two deliberately empty vestibule-adjacent multi-use zones, no seat legs.
   n=f'seat-{side}-{i+1:02d}';p=[sign*1.10,1.61,z];q=[0,math.sin(-sign*math.pi/4),0,math.cos(math.pi/4)]
   v['seats'].append({'seatId':n,'nodeId':n,'frameId':'vehicle','pelvisPointM':p,'cameraEyePointM':[sign*1.08,2.37,z],'facingQuaternionXYZW':q,'humanDatum':'pelvis, not feet','priority':i in [2,5],'anchorNodeId':anchor(n+'-pelvis',p,'interior')});v['collision']['primitives'].append({'id':n,'frameId':'vehicle','nodeId':n,'type':'box','boundsM':bounds([min(sign*.81,sign*1.43),1.47,z-.29],[max(sign*.81,sign*1.43),2.20,z+.29])})
 for i,z in enumerate([-6.4,0,6.4]):
  v['standingRegions'].append({'regionId':'vestibule-'+str(i),'frameId':'vehicle','polygonM':rect(-.66,.66,FLOOR,z-.68,z+.68),'feetPointM':[0,FLOOR,z],'headClearanceM':2.35,'anchorNodeId':anchor('standing-'+str(i),[0,FLOOR,z],'interior')})
 for n,a,b,c,d in [('wheelchair',.35,1.35,.85,2.05),('bicycle-luggage',-1.35,-.35,-2.1,-.85)]:v['freeZones'].append({'zoneId':n,'frameId':'vehicle','polygonM':rect(a,b,FLOOR,c,d),'emptyRequired':True,'note':'Representative clearance, not accessibility certification'})
 for n,p in [('aisle-eye',[0,2.7,-9.6]),('observation-front',[0,2.7,9.65]),('standing-eye',[0,2.72,0])]:v['cameraAnchors'].append({'cameraId':n,'frameId':'vehicle','positionM':p,'nodeId':anchor(n,p,'interior')})
 for n,p in [('front',[0,.68,10.22]),('rear',[0,.68,-10.5])]:v['couplers'].append({'couplerId':n,'frameId':'vehicle','positionM':p,'outwardNormal':[0,0,1 if n=='front' else -1],'anchorNodeId':anchor('coupler-'+n,p)})
 p=[0,FLOOR,-10.25];v['frames'].append({'frameId':'gangway-rear',**transform(p)});v['gangways'].append({'gangwayId':'rear','frameId':'vehicle','gangwayFrameId':'gangway-rear','parentFrameId':'vehicle','positionM':p,'anchorNodeId':anchor('gangway-rear',p),'outwardNormal':[0,0,-1],'walkablePolygonM':rect(-.65,.65,FLOOR,-10.5,-10.15),'clearWidthM':1.3,'clearHeightM':2.13,'telescopingRangeM':[.15,.4],'curveSweep':{'frameId':'vehicle','yawRangeRadians':[-.10,.10],'sweptBoundsM':bounds([-.9,1.0,-10.7],[.9,3.4,-10.1]),'status':'representative envelope, not dynamic-collision acceptance'},'intercarTraversalEnabled':False})
 v['floorSurfaces'].append({'surfaceId':'gangway-floor','nodeId':'body-shell','frameId':'vehicle','resource':'exterior','verticesM':rect(-.65,.65,FLOOR,-10.5,-10.15),'indices':[0,2,1,0,3,2]})
 for n,a,b,node in [('floor',[-1.4,1.02,-10.25],[1.4,FLOOR,10.16],'floor'),('ceiling',[-1.4,3.45,-10.25],[1.4,3.51,10.16],'ceiling'),('observation-wall',[-1.5,FLOOR,10.16],[1.5,3.45,10.25],'body-shell'),('gangway-floor',[-.65,1.02,-10.5],[.65,FLOOR,-10.15],'body-shell'),('gangway-jamb-left',[.65,FLOOR,-10.25],[1.5,3.23,-10.16],'body-shell'),('gangway-jamb-right',[-1.5,FLOOR,-10.25],[-.65,3.23,-10.16],'body-shell'),('gangway-header',[-.8,3.23,-10.5],[.8,3.45,-10.16],'body-shell')]:v['collision']['primitives'].append({'id':n,'frameId':'vehicle','nodeId':node,'type':'box','boundsM':bounds(a,b)})
 v['lodCapabilities']=[{'level':i,'doorsAnimated':i<2,'passengerCapable':i<2,'openingsPreserved':i<2,'interiorLevel':min(i,1) if i<2 else None,'stateRestriction':'Closed empty display only' if i==2 else 'Load interior and validate station before boarding'} for i in range(3)]
 return v

def write_manifest():
 assets=[];measurements=[]
 for variant,kind,n in [('endcar','exterior',3),('shared','interior',2)]:
  aid=f'canada-line-{variant}-{kind}';lods=[];names=set()
  for i in range(n):
   stem=f'{aid}.lod{i}';f='exports/'+stem+'.glb';s='source/'+stem+'.blend';r=common.measure_glb(ROOT/f);names.update(r['materialNames']);lods.append({'level':i,'file':f,'sha256':common.digest(ROOT/f),'source':s,'sourceSha256':common.digest(ROOT/s),**{k:r[k] for k in ['triangles','vertices','primitives','bytes','boundsM','geometryBytes','embeddedImageBytes']},'doorsAnimated':kind=='exterior' and i<2,'passengerCapable':i<2,'openingsPreserved':i<2});measurements.append({'assetId':aid,'level':i,**r})
  assets.append({'id':aid,'taskId':'D04' if kind=='exterior' else 'D05','variant':variant,'kind':kind,'source':lods[0]['source'],'sourceSha256':lods[0]['sourceSha256'],'lods':lods,'boundsM':lods[0]['boundsM'],'expectedDimensionsM':{'bodyLength':20.5,'bodyWidth':3,'floorY':FLOOR,'ceilingUndersideY':3.45},'dimensionToleranceM':.02,'dimensionBasis':'Independent representative Canada Line two-car profile; source-backed visual/type identity, unsurveyed dimension proposal. See references/source-review.json.','pivot':{'frameId':'vehicle','positionM':[0,0,0],'meaning':'Mid-bogie midpoint on rail datum'},'attachmentDatum':{'frameId':'vehicle','type':'rail-contact','planeY':0},'frontAxis':'+Z','materialBindings':[{'material':m,'semanticRole':m.removeprefix('canada-'),'surfaceId':'shared-'+m,'maps':[]} for m in sorted(names)],'textureMode':'shared-role-no-images','textureCost':{'geometryBytes':sum(l['geometryBytes'] for l in lods),'embeddedImageBytes':0,'glbTotalBytes':sum(l['bytes'] for l in lods),'uniqueTexelBytesWithMips':0},'lodPolicy':{'suggestedDistancesM':[45,130] if kind=='exterior' else [25],'hysteresisM':8,'lazyLoad':kind=='interior','passengerLock':'LOD0/1 exterior + interior; LOD2 closed, empty, no boarding'},'clearance':{'floorY':FLOOR,'headroomM':2.35,'doorWidthM':1.5,'doorHeightM':2.13,'aisleWidthM':1.35},'collision':{'type':'JSON-primitives','source':'vehicles[].collision'},'anchors':{'source':'vehicles[].anchors','frameId':'vehicle'},'placementCompatibility':{'profiles':[PROFILE],'scale':[1,1,1],'requires':'Independent Canada Line station alignment; no Expo scaling/relabeling'},'intendedConsumer':'Future explicit Canada Line vehicle adapter. No runtime consumer enabled.','offlineChecks':{'status':'pending','evidence':'qa/validation.json'},'runtimeChecks':{'status':'not_run','integrationStatus':'runtime_pending_webgl'}})
 v=vehicle();v['completeBoundsM']=assets[0]['boundsM'];actual_length=round(2*(10.5+assets[0]['boundsM']['max'][2]),6);m={'schemaVersion':1,'packageId':'canada-line-stage2','version':'1.0.0','baseRevision':BASE,'status':'offline_complete_runtime_pending','units':'m','coordinateSystem':{'runtime':'glTF +Y up, +Z front, -X right','authoring':'Blender +Z up, -Y front','conversion':'(x,y,z) Blender -> (x,z,-y) glTF exactly once'},'provenance':{'author':'Original representative geometry for Vancouver Living Atlas by YiTaChen','source':'https://github.com/YiTaChen/vancouver-living-atlas','license':'Vancouver Living Atlas Noncommercial Research and Attribution 1.0','references':'references/source-review.json','copiedImagesOrMeshes':False,'referenceMediaUse':'Reference review only; not texture or model source','modelIdentity':'Canada Line-inspired two-car representative, not exact Hyundai Rotem replica'},'reexportCommand':'blender -b -t 2 --python tools/assets/canada-line-stage2/export.py -- --output /tmp/canada-line-reexport','validationCommand':'python tools/assets/canada-line-stage2/validate.py','assets':assets,'textures':[],'vehicles':[v],'composition':{'profileId':PROFILE,'frameId':'consist','cars':[{'carId':'canada-car-01','vehicleId':v['vehicleId'],'translationM':[0,0,10.5],'rotationQuaternionXYZW':IDENT},{'carId':'canada-car-02','vehicleId':v['vehicleId'],'translationM':[0,0,-10.5],'rotationQuaternionXYZW':[0,1,0,0]}],'nominalBodyLengthM':41,'actualLengthM':actual_length,'representativeNominalConsistLengthM':41.5,'carPitchM':21,'betweenCarBodyGapM':.5,'requiredPlatformLengthM':actual_length+2,'stoppingToleranceEachEndM':1,'movingIntercarTraversal':'not_supported_pending_seam_and_moving_collision_validation','directionMapping':'Car02 yaw=pi: car-left maps to consist-right. Preserve door IDs and transform normals.'},'runtimeChecks':{'status':'not_run','integrationStatus':'runtime_pending_webgl','D06':'not_implemented','movingIntercarTraversal':'not_run','terrainAndPlatformIntegration':'not_run'}}
 (ROOT/'manifest.json').write_text(json.dumps(m,indent=2)+'\n');(ROOT/'qa/measurements.json').write_text(json.dumps({'status':'measured','method':'Actual transformed GLB scene accessors, CPU','results':measurements,'uniqueTexelBytesWithMips':0,'runtimeGpuMeasured':False},indent=2)+'\n')
if __name__=='__main__':write_manifest()
