"""Refresh base frame manifest, append new optional paired sills and assembly contract."""
import json,copy,runpy,importlib.util,platform
from pathlib import Path
HERE=Path(__file__).resolve().parent
runpy.run_path(str(HERE/'_finalize_frames.py'))
sp=importlib.util.spec_from_file_location('paired_common',HERE.parent/'package-contract/validate.py');common=importlib.util.module_from_spec(sp);sp.loader.exec_module(common)
def write(p,obj):(HERE/p).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
m=json.loads((HERE/'manifest.json').read_text());measure=json.loads((HERE/'qa/measurements.json').read_text());sills=json.loads((HERE/'sill-designs.json').read_text());assemblies=[]
for aid,d in sills.items():
 frame=next(a for a in m['assets'] if a['id']==d['frameId']);a=copy.deepcopy(frame);lods=[]
 for lod in [0,1]:
  source=f'source/{aid}.lod{lod}.blend';file=f'exports/{aid}.lod{lod}.glb';r=common.measure_glb(HERE/file)
  lods.append({'level':lod,'source':source,'sourceSha256':common.digest(HERE/source),'file':file,'sha256':common.digest(HERE/file),**{k:r[k] for k in ['boundsM','triangles','vertices','primitives','bytes','geometryBytes','embeddedImageBytes']},'capabilities':{'slopedDrainageFace':True,'physicalDripOrNose':True,'sharedFrameRoot':True}})
  measure['results'].append({'assetId':aid,'lod':lod,'sourceBytes':(HERE/source).stat().st_size,'sourceSha256':common.digest(HERE/source),'glbSha256':common.digest(HERE/file),'sourceCompression':'Zstandard compressed native section mesh; n-gon caps triangulated only in export memory',**r,'uniqueTexelBytesWithMips':0})
 a.update({'id':aid,'kind':'source-fitted-paired-window-sill','variant':d['variant'],'source':lods[0]['source'],'sourceSha256':lods[0]['sourceSha256'],'lods':lods,'boundsM':lods[0]['boundsM'],'expectedDimensionsM':{'width':d['widthM'],'height':.124,'depth':d['depthM'],'maximumY':-.006,'minimumY':-.13},'dimensionBasis':'Original paired sill based on actual source aperture + twice chosen frame section + 0.14m end projection. Top=windowBounds.bottom-sectionM-0.006m, slope/drop and physical drip are representative proposals. No old sill-slot Y.','pivot':{'positionM':[0,0,0],'meaning':'shared frame root; sill itself occupies negative local Y'},'attachmentDatum':{'kind':'shared-window-frame-root','wallPlaneZ':0,'rootYRule':'windowBounds.bottom - sectionM','sectionM':d['sectionM'],'sillTopYRule':'windowBounds.bottom-sectionM-0.006','localTopY':-.006,'minimumLocalY':-.13,'frameSeparationM':.006,'neverUse':'legacy sill-slot Y or recentered sill bounds'},'clearance':{'kind':'entire-sill-below-frame','maximumLocalY':-.006,'minimumLocalY':-.13,'frameSeparationM':.006,'depthM':d['depthM'],'scope':'strict separated actual GLB bounds below frame; combined aperture triangle/ray checks'},'anchors':[{'id':'shared-frame-root','positionM':[0,0,0]},{'id':'sill-rear-top','positionM':[0,-.006,.02]}],'placementCompatibility':{'frameAssetId':d['frameId'],'scale':[1,1,1],'rootTranslationM':[0,0,0],'fitFunction':'fit.mjs:fitAssembly','requires':'explicit selected old-sill suppression only while optional pair candidate is enabled','oldFilesRemainUnchanged':True,'canopyAndGISWallCollisionRemainUnchanged':True,'sourceIDsAreFixturesNotActivation':True,'fallback':'retain entire existing frame/sill detail if assembly is not admitted'},'offlineChecks':{'status':'pass','evidence':['qa/validation.json','qa/positive-assembly-fixtures.json','qa/assembly-preview-index.json','qa/source-edit-preservation.json','qa/blender-audit.json']}})
 a['materialBindings'][0]['primitiveBindingsByLod']={str(l):[{'node':'window-sill','primitive':0}] for l in [0,1]};a['textureCost']={'geometryBytes':sum(l['geometryBytes'] for l in lods),'embeddedImageBytes':0,'glbTotalBytes':sum(l['bytes'] for l in lods),'uniqueTexelBytesWithMips':0,'newUniqueTexelBytesWithMips':0};a['lodPolicy']['preserve']=['outer bounds','shared frame root','sloped top','physical nose/drip','6mm lower-frame gap'];m['assets'].append(a)
 assemblies.append({'id':d['frameId'].replace('surround','paired-assembly'),'taskId':d['taskId'],'frameId':d['frameId'],'sillId':aid,'commonRoot':'source windowBounds.bottom - chosen frame section','transforms':{'frame':{'translationM':[0,0,0],'scale':[1,1,1]},'sill':{'translationM':[0,0,0],'scale':[1,1,1]}},'existingSillPolicy':'Suppress only the source-selected previous sill descriptor while this optional pair is enabled. Preserve all old source/export files. Restore old detail on fallback/disposal.','frameSillGapM':.006,'sourceFixtureEvidence':'qa/positive-assembly-fixtures.json','geometryEvidence':'qa/validation.json:optionalPairedAssemblies','runtimeStatus':'runtime_pending_webgl','assemblyOfflineStatus':'pass'})
m['version']='1.1.0';m['assemblies']=assemblies;m['provenance']['pairedSillGeneratorSha256']=common.digest(HERE/'build_sills.py');m['provenance']['acceptanceScope']='offline_complete for two optional source-fitted frame + new paired-sill assemblies; only valid when prior sill is explicitly suppressed. No runtime activation.';m['provenance']['legacySillOverlapDiagnostic']='qa/existing-sill-coexistence.json remains negative evidence for the unsafe old-sill + new-frame combination';m['validationCommand']='python3 tools/assets/source-fitted-window-variants/validate.py && node --test tools/assets/source-fitted-window-variants/fit.test.mjs tools/assets/source-fitted-window-variants/assembly.test.mjs && python3 -m unittest discover -s tools/assets/source-fitted-window-variants -p test_validate.py';write('manifest.json',m)
measure['totals']={'glbBytes':sum(r['bytes'] for r in measure['results']),'sourceBytes':sum(r['sourceBytes'] for r in measure['results']),'embeddedImageBytes':0,'newUniqueTexelBytesWithMips':0};write('qa/measurements.json',measure)
h=json.loads((HERE/'qa/handoff.json').read_text());h['assemblies']=assemblies;h['optionalPairOfflineStatus']='pass';h['knownOfflineAssemblyBlocker']['scope']='Only the unsafe new frame + retained OLD sill combination; the new paired sill solves it when selected-old-sill suppression is explicit';h['completed']+=['two new optional paired sills × two LODs','actual combined GLB separating-plane non-overlap, opening rays and source attachment verification','explicit old-sill suppression contract with fallback retained','24 additional actual paired-assembly CPU images'];h['runtimeChecks']['required']=['optional atomic frame and paired-sill replacement, old-sill suppression and restoration','source wall shader alignment at actual foundation','cell caps, material rebinding, bounded LOD','four city lighting conditions and WebGL screenshots','draws, memory, frame time, disposal'];h['nextSteps']=['Call fitAssembly with actual source data and exact existingSillSlotId; require suppressExistingSill=true','Load frame + its matching new paired sill with shared root windowBounds.bottom-sectionM; no transform recentering','Only while optional candidate is admitted, suppress prior selected sill and replaced procedural frame detail; keep old files and restore fallback on removal','Keep cedar canopy ground datum, GIS wall, collision and all source geometry unchanged','Rebind shared semantic material roles, implement bounded LOD/cache/disposal, then run real WebGL acceptance'];write('qa/handoff.json',h)
print('PAIRED_SILL_MANIFEST',len(m['assets']),measure['totals'])
