"""Measure exports, resolve vehicle dependencies and record local research layouts."""
import hashlib,importlib.util,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parent;REPO=ROOT.parents[2]
s=importlib.util.spec_from_file_location('common',ROOT.parent/'package-contract/validate.py');C=importlib.util.module_from_spec(s);s.loader.exec_module(C)
IDENT=[0,0,0,1]
def dump(name,v):(ROOT/name).write_text(json.dumps(v,indent=2)+'\n')
def bounds(lo,hi):return {'min':lo,'max':hi,'size':[b-a for a,b in zip(lo,hi)]}
def rect(x0,x1,z0,z1,y):return [[x0,y,z0],[x1,y,z0],[x1,y,z1],[x0,y,z1]]
def frame(i,p=[0,0,0],q=IDENT,parent=None):return {'frameId':i,'parentFrameId':parent,'translationM':p,'rotationQuaternionXYZW':q,'scale':[1,1,1],'units':'m','upAxis':'+Y','frontAxis':'+Z'}
def dep(pkg):
 p=ROOT.parent/pkg/'manifest.json';m=json.loads(p.read_text());return m,{'packageId':pkg,'manifest':'../'+pkg+'/manifest.json','version':m['version'],'sha256AtLayoutBuild':C.digest(p),'identity':'local-package-dependency; not copied','geometryAuthoritative':True}
def make_layout():
 bus,bd=dep('boardable-bus');metro,md=dep('boardable-metro');shelter,sd=dep('street-furniture-expansion');bv=bus['vehicles'][0];mc=metro['composition'];mv=metro['vehicles'][0];shel=next(a for a in shelter['assets'] if a['id']=='transit-shelter')
 rail=json.loads((REPO/'public/data/railways.json').read_text());rails=[{'routeId':r['id'],'kind':r['kind'],'sourceIds':r.get('sourceIds',[]),'sourceRelationIds':r.get('sourceRelationIds',[]),'sourceTimestamp':r.get('sourceTimestamp'),'lengthM':r.get('lengthM'),'selectedAsStation':False} for r in rail['routes']]
 audit={'status':'complete','method':'Read repository source inventory and exact feature properties; no newly researched geographic placement','inputs':[{'path':p,'sha256':C.digest(REPO/p)} for p in ['public/data/railways.json','public/data/roads.geojson','public/data/paths.geojson','DATA_SOURCES.md','lib/city/city-buses.ts']], 'railCandidates':rails,'railFinding':'Source-backed open-air Expo alignment exists; no platform footprint, surveyed floor, or entry connection record. Existing files omit underground sections. No station selected.','busFinding':'No stop_id, bus_stop or stopId feature metadata in repository roads/paths; procedural city bus route display is not a source-backed stop pair.','decision':'Unplaced representative local layouts; external map, stop IDs, walk-surface and rail-profile selection required before integration','license':'Existing rail geographic source remains ODbL-1.0, © OpenStreetMap contributors. No new geographic geometry copied.'};dump('qa/source-audit.json',audit)
 stops=[]
 for i,p,q in [('a',[-8,0,0],IDENT),('b',[8,0,22],[0,1,0,0])]:
  fid='research-bus-'+i;h=bv['floorSegments'][0]['heightM'];align=[]
  for a in bv['anchors']:
   if not a['anchorId'].startswith('boarding-'):continue
   group=a['anchorId'].removeprefix('boarding-');d=next(d for d in bv['doors'] if d['doorGroupId']==group);z=a['pointM'][2]
   align.append({'doorGroupId':group,'vehicleAnchorId':a['anchorId'],'vehiclePointM':a['pointM'],'stationPointM':a['pointM'],'floorHeightM':h,'doorSillPointM':[-1.25,h,z],'platformEdgePointM':[-1.5,h,z],'horizontalThresholdGapM':.25,'verticalDifferenceM':0,'openingWidthM':d['doorWidthM'],'approachPolygonM':rect(-3,-1.5,z-.75,z+.75,h),'bridgeSurfaceProposal':{'polygonM':rect(-1.5,-1.25,z-d['doorWidthM']/2,z+d['doorWidthM']/2,h),'enabled':False,'condition':'D06 may enable only when stopped, aligned, door open, dynamic collision and support validated'}})
  stops.append({'stopId':fid,'kind':'bus-stop','sourceStopId':None,'provenance':{'classification':'representative-research-layout','source':'docs/AI_AGENT_DEVELOPMENT_BACKLOG.md D01','realServiceOrRoute':False},'geographicPlacement':{'status':'unresolved','worldTransform':None,'reason':'No source-backed stop pair or walk-surface attachment selected'},'localFrame':frame(fid,p,q,'bus-pair-research'),'vehicleFrame':frame('stopped-bus',[0,0,0],IDENT,fid),'vehicleRef':{'packageId':'boardable-bus','profileId':bv['profileId'],'vehicleId':bv['vehicleId']},'approachDirection':[0,0,1],'boardingSide':'right','floorHeightM':h,'floorBasis':'Explicit 0.36m level boarding-island research proposal matched to vehicle; not surveyed curb height','floorPolygonM':rect(-5.7,-1.5,-7,7,h),'waitingPolygons':[{'id':'shelter-waiting','polygonM':rect(-4.83,-4.43,-2.25,.05,h),'purpose':'standing area in shelter, excludes bench'}, {'id':'open-waiting','polygonM':rect(-4.2,-3.4,-2.8,2.8,h),'purpose':'outside approach and through corridor'}],'pedestrianCorridor':{'polygonM':rect(-3.3,-1.5,-7,7,h),'clearWidthM':1.8,'note':'Boarding approaches cross this corridor only during stopped boarding; no permanent obstacle allowed'},'doorAlignmentPoints':align,'entryConnections':[{'connectionId':fid+'-walk-entry','localPointM':[-6.4,h,5.8],'targetWalkSurfaceId':None,'targetPointM':None,'clearWidthM':1.8,'status':'unresolved-world-connection','connectorPolygonM':rect(-8.4,-6.4,4.9,6.7,h)}],'instances':[{'assetId':'bus-stop-pole','packageId':'transit-station-spaces','translationM':[-4,h,6],'rotationQuaternionXYZW':[0,.7071067811865475,0,.7071067811865476],'scale':[1,1,1]}, {'assetId':'transit-shelter','packageId':'street-furniture-expansion','lodFiles':[l['file'] for l in shel['lods']],'translationM':[-4.65,h,-1.1],'rotationQuaternionXYZW':[0,.7071067811865475,0,.7071067811865476],'scale':[1,1,1],'referenceOnly':True,'sourceRootPreserved':True}], 'exclusions':[{'id':'vehicle-approach-envelope','type':'box','boundsM':bounds([-1.45,0,-20],[1.7,3.4,20]),'purpose':'keep road/bus approach free; not a valid pedestrian area'},{'id':'door-sweeps','type':'vehicle-metadata-reference','ref':'boardable-bus/vehicles/0/doors/*/sweptBoundsM'},{'id':'shelter-footprint','type':'polygon','polygonM':rect(-6.17,-4.31,-3.38,1.18,h),'purpose':'shelter structure and bench; standing exception only in named free region'},{'id':'parked-car-door-zone','type':'polygon','polygonM':rect(-1.5,-.6,8,12,h),'minimumWidthM':.9,'purpose':'representative exclusion outside stop island, not a parking placement'}],'boardingGameplayEnabled':False})
 # Place shelter so its front face ends X=-4.31; corridor starts -3.30, leaving 1.01m buffer.
 # Surface must encompass entire shelter footprint, including the rear wall.
 for stop in stops:stop['floorPolygonM']=rect(-6.4,-1.5,-7,7,stop['floorHeightM'])
 floor=mv['floorHeightM'];doors=[]
 for car in mc['cars']:
  v=next(v for v in metro['vehicles'] if v['vehicleId']==car['vehicleId'])
  for a in v['anchors']:
   if not a['nodeId'].startswith('boarding-right-'):continue
   p=a['positionM'];z=p[2]+car['translationM'][2];opening=a['nodeId'].removeprefix('boarding-');d=next(d for d in v['doors'] if d['openingId']==opening)
   doors.append({'carId':car['carId'],'vehicleId':v['vehicleId'],'vehicleAnchorId':a['nodeId'],'carLocalPointM':p,'carToStation':frame(car['carId'],car['translationM'],car['rotationQuaternionXYZW'],'research-metro-platform'),'stationPointM':[p[0],floor,z],'doorSillPointM':[-1.28,floor,z],'platformEdgePointM':[-1.5,floor,z],'horizontalThresholdGapM':.22,'verticalDifferenceM':0,'floorHeightM':floor,'openingWidthM':d['openingWidthM'],'approachPolygonM':rect(-3,-1.5,z-.8,z+.8,floor),'bridgeSurfaceProposal':{'polygonM':rect(-1.5,-1.28,z-.7,z+.7,floor),'enabled':False,'condition':'D06 stopped-and-open state plus gap support and dynamic collision validation'}})
 platform={'stopId':'research-metro-platform','kind':'rail-platform','sourceStopId':None,'provenance':{'classification':'representative-research-layout','railCandidateSource':'qa/source-audit.json','source':'boardable-metro manifest composition and door anchors','realServiceOrRoute':False},'geographicPlacement':{'status':'unresolved','worldTransform':None,'reason':'No surveyed platform, entrance or walk-surface; existing open-air rail alignments only'},'localFrame':frame('research-metro-platform'),'vehicleFrame':frame('stopped-consist',[0,0,0],IDENT,'research-metro-platform'),'vehicleRef':{'packageId':'boardable-metro','profileId':mc['profileId']},'approachDirection':[0,0,1],'boardingSide':'right','floorHeightM':floor,'floorBasis':'Matches explicit rail-contact datum and vehicle sill, not legacy body height','floorPolygonM':rect(-5.5,-1.5,-37,37,floor),'platformWidthM':4,'platformLengthM':74,'consistBoundsM':mc['actualBoundsM'],'consistLengthM':mc['actualLengthM'],'stoppingToleranceEachEndM':1,'actualMarginEachEndM':1.25,'waitingPolygons':[{'id':'waiting-strip','polygonM':rect(-3.05,-2.15,-35.5,35.5,floor),'purpose':'standing waiting strip behind tactile safety buffer'}],'pedestrianCorridor':{'polygonM':rect(-4.95,-3.15,-37,37,floor),'clearWidthM':1.8},'doorAlignmentPoints':doors,'entryConnections':[{'connectionId':'research-platform-walk-entry','localPointM':[-5.5,floor,0],'targetWalkSurfaceId':None,'targetPointM':None,'clearWidthM':1.8,'status':'unresolved-world-connection','connectorPolygonM':rect(-7.5,-4.95,-.9,.9,floor),'levelConnectionOnly':True,'undergroundConnection':False}],'instances':[{'assetId':'platform-edge-2m','packageId':'transit-station-spaces','translationM':[-3.5,0,z],'rotationQuaternionXYZW':IDENT,'scale':[1,1,1]} for z in range(-36,37,2)]+[{'assetId':'station-guidance-sign','packageId':'transit-station-spaces','translationM':[-5.30,floor,18],'rotationQuaternionXYZW':[0,.7071067811865475,0,.7071067811865476],'scale':[1,1,1]}], 'exclusions':[{'id':'track-envelope','type':'box','boundsM':bounds([-1.49,0,-40],[1.49,3.7,40]),'purpose':'no permanent platform furniture or pedestrian path'},{'id':'edge-safety-buffer','type':'polygon','polygonM':rect(-2.15,-1.5,-37,37,floor),'purpose':'keep waiting and furniture out; door approach only when authorized stopped state'},{'id':'door-sweeps','type':'vehicle-metadata-reference','ref':'boardable-metro/vehicles/*/doors/*/sweptBoundsM','transform':'composition cars'},{'id':'guidance-sign-footprint','type':'polygon','polygonM':rect(-5.42,-5.18,17.1,18.9,floor),'purpose':'permanent structural sign posts, outside 1.8m corridor'}],'boardingGameplayEnabled':False,'intercarTraversalEnabled':False}
 layout={'schemaVersion':1,'packageId':'transit-station-spaces','units':'m','coordinateSystem':'glTF Y-up, +Z vehicle approach, -X vehicle right; station modules have explicit track-facing edge +X','scope':'local research layouts only; not geographic route, accessibility certification, or boarding runtime','dependencies':[bd,md,sd],'busPairFrame':frame('bus-pair-research'),'busPairSpatialMeaning':'two opposite-direction research islands; transforms are local scene demonstrations, not world locations','stops':stops+[platform],'runtimeIntegrationStatus':'runtime_pending_webgl','unresolved':['source stop IDs','geographic placement','walk/rail surface attachment','real entrance levels and ramps/lifts','gap support and gameplay state gating','WebGL collision/LOD/performance'],'prohibitedClaims':['No invented Waterfront underground connection','No live route/service claim','No cross-car traversal acceptance']}
 for stop in layout['stops']:
  stop['floorTriangulation']={'indices':[0,2,1,0,3,2],'normal':[0,1,0],'verticesRef':'floorPolygonM'}
  rail=stop['kind']=='rail-platform';aid='metro-threshold-deck' if rail else 'bus-threshold-deck';x0,x1,width=(-.48,.42,1.10) if rail else (-.5,.45,.95)
  for index,d in enumerate(stop['doorAlignmentPoints']):
   z=d['stationPointM'][2];y=stop['floorHeightM'];did='threshold-'+(d['carId']+'-' if rail else '')+d['vehicleAnchorId']
   stored_rotation=[0,0,.7071067811865475,.7071067811865476]
   measured=C.measure_glb(ROOT/'exports'/(aid+'.lod0.glb'))['boundsM'];rotation=C.transform({'rotation':stored_rotation})
   rotated_corners=[C.point(rotation,[x,yy,zz]) for x in [measured['min'][0],measured['max'][0]] for yy in [measured['min'][1],measured['max'][1]] for zz in [measured['min'][2],measured['max'][2]]]
   storage_y=y-min(v[1] for v in rotated_corners)
   storage=[-5.25,storage_y,z] if rail else [-5.9,storage_y,-4.5-index*1.3]
   d.pop('bridgeSurfaceProposal',None)
   d['thresholdDeck']={'instanceId':did,'assetId':aid,'packageId':'transit-station-spaces','frameId':stop['stopId'],'deployedTransform':frame(did,[-1.5,y,z],IDENT,stop['stopId']),'retractedTransform':frame(did+'-stored',storage,stored_rotation,stop['stopId']),'storedFloorContact':{'floorHeightM':y,'bottomHeightM':y,'derivation':'floorY minus minimumY of actual exported LOD0 bounds transformed by stored rotation; validate both LODs against actual GLB vertices','support':'research floor, no hidden holder'},'retractedMeaning':'Portable research plate stored upright at designated station-side storage strip; no automatic folding/slide mechanism or vehicle retrofit implied','transition':'Manual/actor relocation only with boarding area closed; interpolated motion path not yet validated','enabled':False,'activationRequires':['vehicle stopped','correct profile and frame alignment','paired doorway fully open','station support and dynamic collision accepted by D06'],'stationBearingPointM':[-1.5+x0,y,z],'vehicleBearingPointM':[-1.5+x1,y,z],'maximumTopHeightM':y+.015,'maximumRiseM':.015,'maximumGrade':.075,'clearWidthM':width,'walkableSurfaceTriangulation':[0,2,1,0,3,2],'walkableSurfacePolygonsM':[[[-1.5+x0,y,z-width/2],[-1.5+x0+.2,y+.015,z-width/2],[-1.5+x0+.2,y+.015,z+width/2],[-1.5+x0,y,z+width/2]],[[-1.5+x0+.2,y+.015,z-width/2],[-1.5+x1-.2,y+.015,z-width/2],[-1.5+x1-.2,y+.015,z+width/2],[-1.5+x0+.2,y+.015,z+width/2]],[[-1.5+x1-.2,y+.015,z-width/2],[-1.5+x1,y,z-width/2],[-1.5+x1,y,z+width/2],[-1.5+x1-.2,y+.015,z+width/2]]],'doorSweepPolicy':'Plate deploys only after leaves reach their full open endpoint; close doors only after plate is stored','modelNotCertification':True}
   stop['exclusions'].append({'id':did+'-storage','type':'polygon','polygonM':rect(storage[0]-.04,storage[0]+.04,storage[2]-width/2,storage[2]+width/2,y),'purpose':'Upright plate storage footprint outside pedestrian corridor; staff/actor managed research prop'})
 layout['unresolved']=[x for x in layout['unresolved'] if x!='gap support and gameplay state gating']+['threshold deployment motion and D06 gameplay state gating']
 dump('station-layout.json',layout);return layout

def write_manifest():
 layout=make_layout();assets=[];results=[]
 specs={'bus-stop-pole':([.58,2.665,.26],{'type':'ground-contact','planeY':0},[{'id':'ground-contact','pointM':[0,0,0]},{'id':'read-face','pointM':[0,2.285,.1]}]),'platform-edge-2m':([4,.95,2],{'type':'rail-contact-base','planeY':0,'walkSurfaceY':.95},[{'id':'platform-top','pointM':[0,.95,0]},{'id':'track-edge','pointM':[2,.95,0]},{'id':'join-forward','pointM':[0,.95,1]},{'id':'join-back','pointM':[0,.95,-1]}]),'station-guidance-sign':([1.88,2.85,.24],{'type':'ground-contact','planeY':0},[{'id':'ground-contact','pointM':[0,0,0]},{'id':'clear-passage','pointM':[0,0,0]},{'id':'read-face','pointM':[0,2.59,.085]}])}
 for aid,x0,x1,w in [('bus-threshold-deck',-.5,.45,.95),('metro-threshold-deck',-.48,.42,1.10)]:
  specs[aid]=([x1-x0,.035,w],{'type':'platform-edge-floor','planeY':0,'maximumWalkSurfaceY':.015},[{'id':'station-bearing','pointM':[x0,0,0]},{'id':'vehicle-bearing','pointM':[x1,0,0]},{'id':'deck-high-point','pointM':[0,.015,0]}])
 for aid,(expected,datum,anchors) in specs.items():
  lods=[];names=set()
  for l in [0,1]:
   f=f'exports/{aid}.lod{l}.glb';s=f'source/{aid}.lod{l}.blend';r=C.measure_glb(ROOT/f);names.update(r['materialNames']);results.append({'assetId':aid,'lod':l,**r});lods.append({'level':l,'file':f,'sha256':C.digest(ROOT/f),'source':s,'sourceSha256':C.digest(ROOT/s),'sourceBytes':(ROOT/s).stat().st_size,**{k:r[k] for k in ['triangles','vertices','primitives','bytes','boundsM','geometryBytes','embeddedImageBytes']}})
  assets.append({'id':aid,'taskId':'D01','variant':'representative-research','kind':'station-module','source':lods[0]['source'],'sourceSha256':lods[0]['sourceSha256'],'lods':lods,'boundsM':lods[0]['boundsM'],'expectedDimensionsM':expected,'dimensionToleranceM':.02,'dimensionBasis':'Original representative dimensions; platform envelope follows boardable-metro floor profile; no surveyed station reproduction','pivot':{'positionM':[0,0,0],'meaning':'ground or rail-contact base; no bounds recentering'},'attachmentDatum':datum,'frontAxis':'+X track side' if aid=='platform-edge-2m' else '+Z sign face','materialBindings':[{'material':n,'semanticRole':n,'sharedSurfaceId':'station-'+n,'primitiveSelection':{'materialName':n},'maps':[]} for n in sorted(names)],'textureMode':'shared-role-placeholder','textureCost':{'geometryBytes':sum(l['geometryBytes'] for l in lods),'embeddedImageBytes':0,'glbTotalBytes':sum(l['bytes'] for l in lods),'uniqueTexelBytesWithMips':0},'lodPolicy':{'distanceProposalM':[0,40],'hysteresisM':8,'unitScaleOnly':True,'sameDatumAndEnvelope':True,'platformInstancesMayBatchByRole':True},'clearance':{'signUndersideHeightM':2.33,'betweenPostsM':1.63} if aid=='station-guidance-sign' else {'walkSurfaceY':.95,'trackFacingEdgeX':2,'tileLengthM':2} if aid=='platform-edge-2m' else {'avoidPedestrianCorridor':True},'collision':{'type':'JSON-layout-polygons-and-module-AABBs','layoutRef':'station-layout.json','floorSupport':'platform module only; bus local research surfaces remain descriptors'},'anchors':anchors,'placementCompatibility':{'profileIds':['low-floor-bus-12m','expo-metro-17m'],'scale':[1,1,1],'sourceRequirement':'Resolve source station/stop IDs and ground/rail/walk surfaces before geographic placement'},'intendedConsumer':['lib/city/city-buses.ts (future adapter)','lib/city/railway.ts (future adapter)','walk-surface/collision system (future D06 integration)'],'offlineChecks':{'status':'pending','evidence':['qa/validation.json','qa/blender-validation.json','qa/source-edit-proof.json','qa/previews/index.json']},'runtimeChecks':{'status':'not_run','integrationStatus':'runtime_pending_webgl'}})
 for a in assets:
  if a['id'].endswith('threshold-deck'):
   w=.95 if a['id'].startswith('bus') else 1.10
   a['kind']='portable-threshold-deck';a['pivot']={'positionM':[0,0,0],'meaning':'station edge floor datum at local X=0; +X crosses gap toward vehicle'};a['frontAxis']='+X toward vehicle';a['clearance']={'clearWidthM':w,'maximumDeckRiseM':.015,'taperRunM':.20,'maximumGrade':.075,'source':'station-layout.json stops[].doorAlignmentPoints[].thresholdDeck'};a['collision']={'type':'actual deck mesh plus three top walk polygons','metadata':'station-layout.json stops[].doorAlignmentPoints[].thresholdDeck.walkableSurfacePolygonsM','stateGate':'deployed only after matching doorway fully open; stow before door closing'}
 m={'schemaVersion':1,'packageId':'transit-station-spaces','version':'1.0.0','baseRevision':subprocess.check_output(['git','rev-parse','HEAD'],cwd=REPO,text=True).strip(),'status':'offline_validation_pending','units':'m','coordinateSystem':{'authoring':'Blender Z-up, -Y forward','runtime':'glTF Y-up, +Z sign front/vehicle approach','conversion':'Blender(x,y,z) -> glTF(x,z,-y) exactly once','platformTrackFacingEdge':'+X'},'provenance':{'project':'Vancouver Living Atlas by YiTaChen','source':'https://github.com/YiTaChen/vancouver-living-atlas','license':'Vancouver Living Atlas Noncommercial Research and Attribution 1.0','authoring':'Original editable procedural mesh; no downloaded logos, fonts, photos or artwork','references':['docs/AI_AGENT_DEVELOPMENT_BACKLOG.md D01 and common contract','boardable-bus/manifest.json','boardable-metro/manifest.json','street-furniture-expansion/manifest.json'],'geographicAudit':'qa/source-audit.json'},'reexportCommand':'blender -b -t 2 --python tools/assets/transit-station-spaces/export.py -- --output /tmp/station-reexport','validationCommand':'python tools/assets/transit-station-spaces/validate.py','assets':assets,'textures':[],'dependencies':layout['dependencies'],'stationLayout':'station-layout.json','scope':'offline_only','thresholdModules':{'deployedStates':'station-layout.json stops[].doorAlignmentPoints[].thresholdDeck','motionPolicy':'Portable research decks; static stored/deployed poses only, no interpolated deployment acceptance','collisionGeometry':'threshold deck mesh with three top support polygons','certification':False},'runtimeChecks':{'status':'not_run','integrationStatus':'runtime_pending_webgl'}};m['staticExportBatching']={'status':'enabled','method':'lossless material and attribute signature batching','actorRoot':'station-module-root','originalParts':'Editable .blend parts unchanged; original GLB nodes retained as zero-draw component anchors','geometryLookup':'Batch node extras.componentRanges indexes its sole mesh primitive; sourceLocalToModuleMatrix records original component frame','evidence':'qa/static-batching.json','notInstancing':True,'runtimeGpuDrawsMeasured':False}
 for asset in m['assets']:
  for lod in asset['lods']:
   doc,_=C.read_glb(ROOT/lod['file']);meta=doc['extras']['staticBatching'];lod['staticBatching']={'sourceMeshNodeCount':meta['sourceMeshNodeCount'],'renderPrimitiveCount':meta['renderPrimitiveCount'],'componentRanges':'nodes[].extras.componentRanges','actorRoot':'station-module-root'}
 dump('manifest.json',m);dump('qa/measurements.json',{'status':'measured','method':'actual ordinary GLB scene-node transformed accessors','environment':{'Blender':'4.3.2','device':'CPU','threads':2},'results':results,'uniqueTexelBytesWithMips':0,'gpuMeasured':False})
if __name__=='__main__':write_manifest()
