"""Refresh measurements only after the editable source exporter has run."""
import importlib.util, json, subprocess, hashlib
from pathlib import Path
import sys
sys.dont_write_bytecode = True
P=Path(__file__).resolve().parent
spec=importlib.util.spec_from_file_location('common',P.parent/'package-contract'/'validate.py');common=importlib.util.module_from_spec(spec);spec.loader.exec_module(common)
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
assets=[]
for aid,roles,expected,anchor in [
 ('lecture-chair-module',['interior-oak-veneer','landmark-brushed-aluminum'],[.62,1.0075,.6075],{'seatTopM':[0,.45,0]}),
 ('admissions-counter-module',['interior-oak-veneer','interior-matte-plaster'],[1.5,1.1,1.5],{'worktopM':[0,1.1,0]}),
]:
    lods=[]
    for level in [0,1]:
        source=f'source/{aid}.lod{level}.blend';file=f'exports/{aid}.lod{level}.glb';r=common.measure_glb(P/file)
        doc,_=common.read_glb(P/file)
        batching={**doc['extras']['staticBatching'],'actorRoot':'furniture-module-root','batches':[{'nodeId':n['name'],'material':doc['materials'][doc['meshes'][n['mesh']]['primitives'][0]['material']]['name'],'componentRanges':n['extras']['componentRanges']} for n in doc['nodes'] if 'mesh' in n]}
        lods.append({'staticBatching':batching,'level':level,'file':file,'sha256':sha(P/file),'source':source,'sourceSha256':sha(P/source),**r})
    assets.append({'id':aid,'taskId':'E04','variant':'representative-shared-oak','kind':'interior-furniture-module','source':lods[0]['source'],'sourceSha256':lods[0]['sourceSha256'],'lods':lods,'boundsM':lods[0]['boundsM'],'expectedDimensionsM':expected,'dimensionToleranceM':.02,'dimensionBasis':'Current source furniture use/footprint; human-scale representative redesign inside old collision. Seat top .45; admissions counter top1.1. Not a measured real building furnishing.','pivot':{'positionM':[0,0,0],'description':'Ground contact centre, no rescale/recentre at integration'},'attachmentDatum':{'kind':'existing-site-floor','yM':0},'frontAxis':'+Z','materialBindings':[{'glbMaterial':'EXPORT_'+r,'semanticRole':r,'surfaceId':r,'mapsCatalog':'shared-surface-catalog.json','uvUnit':'metres','repeatPerMetre':1} for r in roles],'textureMode':'named-role-placeholders; bind existing shared maps externally','textureCost':{'geometryBytes':sum(l['geometryBytes'] for l in lods),'embeddedImageBytes':0,'glbTotalBytes':sum(l['bytes'] for l in lods),'newUniqueTexelBytesWithMips':0,'referencedSharedTexelBytesWithMips':len(roles)*1048576},'lodPolicy':{'proposalSwitchM':[0,25],'hysteresisM':3,'note':'Candidate only. Select near seated/interaction view at LOD0; CPU cost measured, runtime distance not accepted.'},'clearance':{'rule':'All measured LOD bounds must remain inside existing blocked footprint. No new route/door obstruction.'},'collision':{'mode':'retain-source-rectangle','sizeM':[.65,1.05,.7] if aid.startswith('lecture') else [1.5,1.1,1.5]},'anchors':anchor,'placementCompatibility':{'plan':'adapters/furniture-plan.mjs','scale':[1,1,1],'usage':'Canada lecture chair 54 source instances' if aid.startswith('lecture') else 'Science admissions four modules within existing single6m counter','exclusions':['No blanket hall replacement','No table use invented','Keep current signs/screens/obstacles/doors/floors']},'intendedConsumer':'lib/city/interiors.ts source-callsite replacement, not active','offlineChecks':{'status':'pass','evidence':['qa/blender-validation.json','qa/common-validation.json','qa/consumer-validation.json','qa/furniture-fit.json','qa/static-batching.json']},'staticBatching':{'scope':'export-only, two role primitives per LOD; source objects/modifiers are never merged','nodeContract':'Original named parts are zero-draw anchors. Geometry is in furniture-batch-* nodes; componentRanges address exact vertex/index slices.','costEvidence':'qa/static-batching.json'},'runtimeChecks':{'status':'not_run','reason':'WebGL integration, shader appearance, normal seams, draw/frame/memory, actual gameplay and rollout pending'}})
manifest={'schemaVersion':1,'packageId':'material-consumer-candidates','version':'1.1.0','baseRevision':subprocess.check_output(['git','rev-parse','HEAD'],cwd=P).decode().strip(),'status':'offline_complete; runtime_pending_webgl','units':'m','coordinateSystem':{'authoring':'Blender Z-up','exports':'glTF Y-up','conversion':'(x,y,z) -> (x,z,-y), once at export','consumerGeometry':'Original Three Y-up, Roadster +Z and unmodified root; source patches do not axis-convert'},'provenance':{'author':'Original procedural modules and consumer adapters based on this repository','source':'https://github.com/YiTaChen/vancouver-living-atlas','license':'Repository LICENSE, Vancouver Living Atlas Noncommercial Research and Attribution 1.0','sharedTextures':'Existing role-materials only; no duplicated/new PNGs','reviewedSourceHashes':'qa/current-source-fixtures.json'},'reexportCommand':'blender -b --factory-startup -t 2 --python-exit-code 1 --python tools/assets/material-consumer-candidates/build.py -- --from-source tools/assets/material-consumer-candidates/source/lecture-chair-module.lod0.blend --output tools/assets/material-consumer-candidates/exports/lecture-chair-module.lod0.glb','validationCommand':'python tools/assets/material-consumer-candidates/validate.py','assets':assets,'textures':{'new':[],'sharedCatalog':'shared-surface-catalog.json','surfaceCount':8,'mapCount':24,'uniqueRGBA8FullMipEstimateBytes':8388608,'note':'Referenced cost across all eight IDs; existing maps unchanged. Per-asset shared costs cannot be summed as unique.'},'consumerCandidates':{'E02':{'entry':'adapters/consumer-candidates.mjs:makeRoadsterCandidate','status':'offline_complete','runtime':'not_integrated'},'E04':{'entry':'adapters/consumer-candidates.mjs:makeInteriorsCandidate','status':'offline_complete','runtime':'not_integrated'},'E03':{'entry':'qa/harbour-aircraft-gap-audit.json','status':'offline_audit_complete_no_verified_asset_gap','runtime':'unchanged'},'F05':{'entry':'adapters/shared-surfaces.mjs','status':'offline_complete','runtime':'not_integrated'}}}
(P/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
report=common.validate(P);(P/'qa'/'common-validation.json').write_text(json.dumps(report,indent=2)+'\n')
(P/'qa'/'measurements.json').write_text(json.dumps({'status':'pass','assets':[{'id':a['id'],'lods':a['lods']} for a in assets],'newTextureBytes':0,'sourcesBytes':sum((P/l['source']).stat().st_size for a in assets for l in a['lods']),'glbBytes':sum(l['bytes'] for a in assets for l in a['lods']),'notes':'Measured CPU source/export files; no GPU/VRAM/frame acceptance.'},indent=2)+'\n')
print([(a['id'],[(l['level'],l['triangles'],l['primitives'],l['bytes']) for l in a['lods']]) for a in assets])
