"""Measure real exports and publish honest offline manifests. No synthetic acceptance."""
import json,sys,hashlib,importlib.util
from pathlib import Path
ROOT=Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT));from layout import dump,digest,COLORS
spec=importlib.util.spec_from_file_location('common',ROOT.parent/'package-contract/validate.py');C=importlib.util.module_from_spec(spec);spec.loader.exec_module(C)
l=json.loads((ROOT/'station-layout.json').read_text());m={'schemaVersion':1,'packageId':'skytrain-stations-stage2','version':'1.0.0','baseRevision':'9efce79601deac6a0648cf8e158f3935cbb46f51','status':'offline_representative_supplement','units':'m','coordinateSystem':{'runtime':'glTF Y-up +Z representative track direction','authoring':'Blender Z-up -Y track direction','conversion':'(x,y,z) Blender -> (x,z,-y) glTF exactly once'},'provenance':{'project':'Vancouver Living Atlas by YiTaChen','source':'https://github.com/YiTaChen/vancouver-living-atlas','license':'Vancouver Living Atlas Noncommercial Research and Attribution 1.0; repository LICENSE applies','authoring':'Original procedural meshes; no copied photo pixels, logos, artwork or third-party meshes','sourceAudit':'qa/source-audit.json','notSurveyed':True},'reexportCommand':'blender -b -t 2 --python tools/assets/skytrain-stations-stage2/export.py','validationCommand':'python tools/assets/skytrain-stations-stage2/validate.py','layoutRef':'station-layout.json','textures':[],'assets':[],'runtimeChecks':{'webgl':'not_run','terrainAndTrackPlacement':'not_run','boarding':'not_run','nightLighting':'excluded'}};measure=[]
for s in l['stations']:
 sid=s['stationId'];glb=ROOT/'exports'/f'{sid}.glb';source=ROOT/'source'/f'{sid}.blend';r=C.measure_glb(glb);measure.append({'stationId':sid,**r});lod={'level':0,'file':str(glb.relative_to(ROOT)),'sha256':digest(glb),'source':str(source.relative_to(ROOT)),'sourceSha256':digest(source),'sourceBytes':source.stat().st_size,**{k:r[k] for k in ['triangles','vertices','primitives','bytes','boundsM','geometryBytes','embeddedImageBytes']}}
 a={'id':sid,'taskId':'D01','variant':s['layoutKind'],'kind':'station-layout','source':lod['source'],'sourceSha256':lod['sourceSha256'],'lods':[lod],'boundsM':r['boundsM'],'expectedDimensionsM':r['boundsM']['size'],'dimensionToleranceM':.02,'dimensionBasis':'Bounds measured from actual GLB, not independent survey targets. Platform lengths 74 m Expo / 44 m Canada; all other dimensions illustrative.','pivot':{'positionM':[0,0,0],'meaning':'local street datum; never recenter by bounds'},'attachmentDatum':{'type':'station-local-street','planeY':0,'worldYUnresolved':True},'frontAxis':'+Z representative track axis','materialBindings':[{'material':mat,'semanticRole':mat,'sharedSurfaceId':'skytrain-stage2-'+mat,'primitiveSelection':{'materialName':mat},'maps':[]} for mat in r['materialNames']],'textureMode':'shared-role-placeholder','textureCost':{'geometryBytes':r['geometryBytes'],'embeddedImageBytes':0,'glbTotalBytes':r['bytes'],'uniqueTexelBytesWithMips':0},'lodPolicy':{'singleNearDetailLOD':True,'globalResident':False,'distanceProposalM':80,'runtimeBudgetValidation':'not_run','sharedGeometry':'batched by role/material; individual walk surfaces retained','terrainCutoutRequired':True},'clearance':{'stationLayoutRef':'station-layout.json','humanReferenceM':1.81,'platformRoofClearanceM':3.55,'certification':False},'collision':{'type':'layout-surfaces-plus-oriented-obstacles-and-track-exclusion','layoutRef':'station-layout.json','dynamicElevatorAndBoarding':'not_implemented'},'anchors':s['anchors'],'placementCompatibility':{'frameId':sid,'localToWorld':s['localToWorld'],'sourceGeographicAnchor':s['geographicAnchor'],'ready':False},'intendedConsumer':'D06 integration agent; offline geometry and interface validation only','offlineChecks':{'commonGLBMeasured':True,'editableSourceExists':True,'sourceMapPixelsInspected':True,'topology':'qa/validation.json','actualGlbCpuPreview':'qa/previews/index.json'},'runtimeChecks':s['runtimeChecks']};m['assets'].append(a)
dump('manifest.json',m);dump('qa/measurements.json',{'status':'measured','method':'common package-contract GLB accessor + node transform audit','assets':measure,'totalTriangles':sum(r['triangles'] for r in measure),'totalGlbBytes':sum(r['bytes'] for r in measure)})
print('measured',len(measure),'GLBs',sum(r['triangles'] for r in measure),'triangles')
# Modules are independent editable resources, while station files contain stored instances.
import copy
for line in ['expo','canada']:
 aid='threshold-bridge-'+line;glb=ROOT/'exports'/f'{aid}.glb';source=ROOT/'source'/f'{aid}.blend';r=C.measure_glb(glb);a=copy.deepcopy(m['assets'][0]);a.update(id=aid,variant='representative-deployable-threshold',kind='station-module',source=str(source.relative_to(ROOT)),sourceSha256=digest(source),boundsM=r['boundsM'],expectedDimensionsM=[.24 if line=='canada' else .22,.015,1.3],dimensionBasis='Original portable bridge; root on upper face, deployed bottom rests on vehicle sill and platform; top rises15mm',pivot={'positionM':[0,0,0],'meaning':'upper-face centre'},attachmentDatum={'type':'conditional-boarding-surface','planeY':0},anchors=[{'id':'top-centre','pointM':[0,0,0]}],placementCompatibility={'layoutRef':'station-layout.json','line':line,'useOnlyPairedDoorInstancePoses':True},runtimeChecks={'deploymentAndCollision':'not_run','readyForBoarding':False});a['lods']=[{'level':0,'file':str(glb.relative_to(ROOT)),'sha256':digest(glb),'source':str(source.relative_to(ROOT)),'sourceSha256':digest(source),'sourceBytes':source.stat().st_size,**{k:r[k] for k in ['triangles','vertices','primitives','bytes','boundsM','geometryBytes','embeddedImageBytes']}}];a['materialBindings']=[{'material':'steel','semanticRole':'threshold-bridge','sharedSurfaceId':'skytrain-stage2-steel','primitiveSelection':{'materialName':'steel'},'maps':[]}];a['textureCost']={'geometryBytes':r['geometryBytes'],'embeddedImageBytes':0,'glbTotalBytes':r['bytes'],'uniqueTexelBytesWithMips':0};m['assets'].append(a);measure.append({'stationId':aid,**r})
dump('manifest.json',m);dump('qa/measurements.json',{'status':'measured','method':'common package-contract GLB accessor + node transform audit','assets':measure,'totalTriangles':sum(r['triangles'] for r in measure),'totalGlbBytes':sum(r['bytes'] for r in measure)})
