import json,importlib.util
from pathlib import Path
ROOT=Path(__file__).resolve().parent
s=importlib.util.spec_from_file_location('audit',ROOT/'validate.py');v=importlib.util.module_from_spec(s);s.loader.exec_module(v)
assets=[]
for f in sorted((ROOT/'exports').glob('*.glb')):
 source='source/'+f.stem+'.blend';measure=v.audit(f)
 assets.append({'id':f.stem,'file':str(f.relative_to(ROOT)),'source':source,'sha256':v.c.digest(f),'sourceSha256':v.c.digest(ROOT/source),'measurements':measure,'skeletonBones':14,'animationClips':sorted(v.CLIPS),'datum':'standing foot sole y=0; sit animation is representative seated pose, align pelvis bone explicitly','collision':{'kind':'capsule','radiusM':.29,'heightM':measure['boundsM']['size'][1]},'productionEnabled':False})
m={'schemaVersion':1,'packageId':'city-life-interactive','units':'m','baseRevision':'9efce79601deac6a0648cf8e158f3935cbb46f51','status':'offline_candidate','integrationStatus':'runtime_pending_webgl','coordinateSystem':{'authoring':'Blender +Z up -Y front','runtime':'glTF +Y up +Z front'},'provenance':{'description':'Original project silhouette refinement with authored 14-bone skin and six clips; reconstructed 2026-10-09, not byte recovery of old unpublished files','baseGenerator':'tools/assets/city-life-pedestrians/build.py','baseGeneratorSha256':v.c.digest(ROOT.parent/'city-life-pedestrians/build.py'),'generatorSha256':v.c.digest(ROOT/'build.py'),'license':'Vancouver Living Atlas Noncommercial Research and Attribution 1.0'},'assets':assets,'textures':[],'runtimeChecks':{'status':'not_run','required':['skin/normal and depth pass rendering','foot slide and self intersection','seat pelvis/door clearance on actual vehicle','upgrade/downgrade identity and phase','bounded mixers and shared resource lifetime','touch and hidden-tab behavior']},'cost':{'geometryBytes':sum(a['measurements']['bytes'] for a in assets),'textureBytes':0,'maximumNearSkeletons':4,'notMeasured':'GPU draw/frame/performance'}}
m.update(version='1.0.0',reexportCommand='blender -b -t 2 --python-exit-code 1 --python tools/assets/city-life-interactive/export.py -- --output /tmp/interactive-reexport',validationCommand='python3 tools/assets/city-life-interactive/validate.py')
for a in assets:
 measure=a['measurements'];height=measure['boundsM']['size'][1]
 a.update(taskId='CITY-LIFE-NEAR',variant=a['id'].removeprefix('pedestrian-'),kind='near-interactive-character',lods=[dict(level=0,file=a['file'],source=a['source'],sha256=a['sha256'],sourceSha256=a['sourceSha256'],**measure)],boundsM=measure['boundsM'],expectedDimensionsM={'dressedHeight':height},dimensionToleranceM=.02,dimensionBasis='original modeled geometry, actual rest-pose accessor measurement',pivot={'translationM':[0,0,0],'datum':'foot-sole'},attachmentDatum='feet at standing root; seated pelvis bone must be aligned',frontAxis='+Z',materialBindings=[{'material':measure['materialNames'][0],'role':'opaque-vertex-color'}],textureMode='vertex-color',textureCost={'downloadBytes':0,'gpuBytesWithMips':0},lodPolicy={'nearOnly':True,'fallback':'original matching rigid-limb-v1 background silhouette','maximumSharedNearSkeletons':4},clearance={'runtimeDoorAndSeatFit':'not_run','measuredRestHeightM':height},anchors={'standingFeetM':[0,0,0],'seatedPelvisBone':'pelvis'},placementCompatibility={'requiresSameSurfaceIdentity':True,'uniformScaleOnly':True},intendedConsumer={'module':'lib/city/city-life/interactive-renderer-candidate.ts','productionEnabled':False},offlineChecks={'geometryAndSkin':'pass','sourceReexport':'qa/source-roundtrip.json','CPUPreviews':'qa/preview-evidence.json'},runtimeChecks={'status':'not_run'})
(ROOT/'manifest.json').write_text(json.dumps(m,indent=2)+'\n');print(v.validate())
