"""Refresh reports only after actual CPU/Blender/render evidence and an explicit visual review exist."""
import hashlib,json,platform,subprocess
from pathlib import Path
import validate as v
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[2]
def read(p):return json.loads((HERE/p).read_text())
def write(p,x):(HERE/p).write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
m=read('manifest.json');validation=v.validate(HERE);blender=read('qa/blender-audit.json');edit=read('qa/source-edit-test.json');preview=read('qa/preview-index.json');visual=read('qa/visual-review.json')
assert blender['status']==edit['status']==visual['status']=='pass'
assert len(blender['sourceAndReimportChecks'])==18 and all(r['sourcePreservingReexport']=='pass' for r in blender['sourceAndReimportChecks'])
assert len(preview['renders'])==44
for r in preview['renders']:assert sha(HERE/r['file'])==r['sha256']
assert visual['reviewedPreviewIndexSha256']==sha(HERE/'qa/preview-index.json'),'render evidence changed since review'
result=subprocess.run(['python3',str(HERE/'test_validate.py')],capture_output=True,text=True);assert result.returncode==0; (HERE/'qa/tests.log').write_text(result.stdout+result.stderr)
for a in m['assets']:a['offlineChecks']['status']='pass';a['offlineChecks']['evidence']=list(dict.fromkeys(a['offlineChecks']['evidence']+['qa/visual-review.json','qa/measurements.json']))
m['status']='offline_complete';write('manifest.json',m)
write('qa/common-validation.json',v.contract.validate(HERE));write('qa/validation.json',v.validate(HERE))
assets=[]
for a in m['assets']:
    assets.append({'id':a['id'],'sourceBytesByLOD':[(HERE/l['source']).stat().st_size for l in a['lods']],'lods':a['lods'],'textureCost':a['textureCost']})
measure={'schemaVersion':1,'status':'pass','packageId':m['packageId'],'baseRevision':m['baseRevision'],'environment':{'python':platform.python_version(),'platform':platform.platform(),'blender':blender['blenderVersion'],'CPUThreads':2},'totals':{'sourceFiles':18,'sourceBytes':sum((HERE/l['source']).stat().st_size for a in m['assets'] for l in a['lods']),'glbFiles':18,'glbTotalBytes':sum(l['bytes'] for a in m['assets'] for l in a['lods']),'geometryBytes':sum(l['geometryBytes'] for a in m['assets'] for l in a['lods']),'embeddedImageBytes':0,'uniqueTexelBytesWithMips':0,'templatesOneEachTrianglesByLOD':[sum(a['lods'][l]['triangles'] for a in m['assets']) for l in range(3)],'materialRoles':3},'assets':assets,'assemblyCosts':validation['assemblyCosts'],'costInterpretation':'Unique files are download cost; assembly cost repeats template bytes per instance conservatively before cache. Geometry bytes include GLB headers/JSON/padding. No GPU allocation, WebGL draw or frame-time measurement.'}
write('qa/measurements.json',measure)
fingerprints=[]
for name in ['lib/city/interiors.ts','lib/city/assets/marine-entry.ts','docs/AI_AGENT_DEVELOPMENT_BACKLOG.md','docs/PROJECT_SPECIFICATION.md','docs/MATERIAL_PIPELINE.md','docs/OFFLINE_ASSET_INTEGRATION_2026_10.md','docs/CITY_READABILITY_2026_10.md','LICENSE']:
    path=REPO/name;record={'file':name,'sha256':sha(path)}
    if name.startswith('lib/'):
        original=subprocess.check_output(['git','show',m['baseRevision']+':'+name],cwd=REPO);record['baseRevisionSha256']=hashlib.sha256(original).hexdigest();record['unchangedFromBaseRevision']=record['sha256']==record['baseRevisionSha256'];assert record['unchangedFromBaseRevision']
    fingerprints.append(record)
write('qa/source-fingerprints.json',{'baseRevision':m['baseRevision'],'files':fingerprints})
write('qa/verification.json',{'status':'pass','CPU':{'packageValidator':'pass','commonContract':'pass','tests':{'status':'pass','passed':15,'failed':0,'evidence':'tests.log'}},'Blender':{'sourceReopen':18,'actualGLBReimport':18,'byteIdenticalPreservingReexport':18,'sourceEditTest':'pass','CyclesCPURenders':44,'humanReferencesMeasuredM':[1.75,1.81],'QAReferenceRulerNominalLengthM':1},'visualReview':'pass','runtimeChecks':{'status':'not_run','reason':'Offline package only; no GPU city scene, performance, lifecycle or gameplay acceptance'},'productionBuild':{'status':'not_run','reason':'Parent integration task owns final repository build and all-new-package isolation'},'sourcesPreserved':True})
write('qa/handoff.json',{'schemaVersion':1,'packageId':m['packageId'],'baseRevision':m['baseRevision'],'taskIds':['B04'],'assetStatus':'offline_complete','integrationStatus':'runtime_pending_webgl','webglAvailable':False,'manifest':'../manifest.json','assemblyPlan':'../assembly-plan.json','sourceEditsPreserved':True,'offlineEvidence':['validation.json','common-validation.json','measurements.json','blender-audit.json','source-edit-test.json','preview-index.json','visual-review.json','verification.json','source-fingerprints.json'],'runtimeChecks':{'status':'not_run','reason':'No city WebGL acceptance; offline Cycles CPU is not browser evidence'},'intendedConsumers':['lib/city/interiors.ts','lib/city/assets/marine-entry.ts'],'replaces':['Waterfront six .6-radius x 8 m columns and 1.6 x .35 x 1.6 m capitals','Marine original terracotta decoration batch','Marine upper transom grille only'],'additive':['Waterfront existing 28 x 3.5 m pediment front moulding','one existing upper 3 x 5 m window surround pilot'],'retains':['building shells, source geometry and original placements','existing collision and closed Marine solidFootprints','Waterfront entrance opening and doors','Marine glass, door frames, revolving drum, lobby and night-light roles'],'materialReuse':['shared sandstone','texture-free shared marine-terracotta','texture-free shared marine-copper'],'knownLimitations':['Original architectural interpretation, not a surveyed restoration or copied artwork','LOD0/1 window is intentionally identical 64-triangle detail','LOD2 deliberately simplifies column fluting, capital profile, archivolt layers and fan bars; sample-test switching distances','No new door action, interior or Marine navigability','All 13 upper windows are eligible source positions but only one-window pilot is budgeted here; expansion requires runtime residency review','Preview assembly omits retained shells, pediment infill and entablature; these must remain in integration','CPU ray sampling verifies exported openings but is not a gameplay collision certification','Source build logged harmless Blender read-only extension-cache warnings; artifact saves and hashes passed','Denoising disabled because this Blender build lacks OpenImageDenoise; previews use 16 CPU samples'],'nextIntegrationSteps':['Use assembly-plan source-local transforms at scale 1; apply Marine thresholdY-.16 once','Suppress exactly replaced procedural pieces, preserve shells/glazing/night/collision','Bind semantic shared materials and preserve UVs rather than using current UV-stripping Parts.add blindly','Load candidate only in controlled source-selected QA; establish LOD/cache/fallback/disposal','Run same-camera WebGL clear/overcast/dusk/night, entry clearances and walking/driving checks','Run final repository checks/build and new-package production isolation before any rollout'],'commitStatus':'not committed by asset worker','publicRuntimeModified':False})
print(json.dumps({'status':'offline_complete','totals':measure['totals']},indent=2))
